/**
 * ****************************************************************************
 * @file reg_rf.h
 * @author SLC(SC) software team. 
 * @brief 
 * @version  1.0
 * ****************************************************************************
 * 
 * THIS CODE IS LIMITED TO GUIDE THE APPLICATION AND IMPROVE THE EFFICIENCY OF RESEARCH AND DEVELOPMENT.
 * AS A RESULT, SILICONDUCTOR IS NOT RESPONSIBLE FOR ANY CLAIMS ARISING DIRECTLY OR INDIRECTLY FROM SUCH FIRMWARE AND/OR CONTENT.
 * 
 * Copyright (c) 2025 Siliconductor Semiconductor all rights reserved.
 * 
 * ****************************************************************************
 */

#ifndef __REG_RF_H__
#define __REG_RF_H__

typedef struct
{
    __IOM uint32_t CHIP_ID;          // 0x00
    __IOM uint32_t PWR_CTRL;         // 0x04
    __IOM uint32_t CRG_CTRL;         // 0x08
    __IOM uint32_t PMU_PD_CFG;       // 0x0C
    __IOM uint32_t CMU_PD_CFG;       // 0x10
    __IOM uint32_t CMU_FSO_CTRL;     // 0x14
    __IOM uint32_t PMU_CTRL;         // 0x18
    __IOM uint32_t PMU_RESERVE;      // 0x1C
    __IOM uint32_t DCDC_CTRL;        // 0x20
    __IOM uint32_t DCDC_RESERVE;     // 0x24
    __IOM uint32_t RC32K_CTRL;       // 0x28
    __IOM uint32_t XTAL32K_CTRL;     // 0x2C
    __IOM uint32_t RC50M_CTRL;       // 0x30
    __IOM uint32_t XTAL25M_TUNE;     // 0x34
    __IOM uint32_t XTAL25M_CTRL;     // 0x38
    __IOM uint32_t TCXO25M_CTRL;     // 0x3C
    __IOM uint32_t FDB_50M_TUNE;     // 0x40
    __IOM uint32_t CMU_BUF_CTRL;     // 0x44
    __IOM uint32_t CMU_BUF_TRIM;     // 0x48
    __IOM uint32_t CMU_RESERVE;      // 0x4C
    __IOM uint32_t INT_ENABLE;       // 0x50
    __IOM uint32_t INT_FLAG;         // 0x54
    __IOM uint32_t INT_CLEAR;        // 0x58
} rf_pmu_handle_t;

#define RF_PMU_RX_DATA_CLK_SEL_SHIFT        (0)
#define RF_PMU_RX_DATA_CLK_SEL_MASK         (0x1U << RF_PMU_RX_DATA_CLK_SEL_SHIFT)
#define RF_PMU_RX_DATA_CLK_SEL_VAL(x)       (((uint32_t)(x) << RF_PMU_RX_DATA_CLK_SEL_SHIFT) & RF_PMU_RX_DATA_CLK_SEL_MASK)
#define RF_PMU_RFFE_PMU_RSTN_SHIFT          (16)
#define RF_PMU_RFFE_PMU_RSTN_MASK           (0x1U << RF_PMU_RFFE_PMU_RSTN_SHIFT)
#define RF_PMU_RFFE_PMU_RSTN_VAL(x)         (((uint32_t)(x) << RF_PMU_RFFE_PMU_RSTN_SHIFT) & RF_PMU_RFFE_PMU_RSTN_MASK)
#define RF_PMU_REG_PMU_RSTN_SHIFT           (17)
#define RF_PMU_REG_PMU_RSTN_MASK            (0x1U << RF_PMU_REG_PMU_RSTN_SHIFT)
#define RF_PMU_REG_PMU_RSTN_VAL(x)          (((uint32_t)(x) << RF_PMU_REG_PMU_RSTN_SHIFT) & RF_PMU_REG_PMU_RSTN_MASK)
#define RF_PMU_RFFE_CTRL_RSTN_SHIFT         (20)
#define RF_PMU_RFFE_CTRL_RSTN_MASK          (0x1U << RF_PMU_RFFE_CTRL_RSTN_SHIFT)
#define RF_PMU_RFFE_CTRL_RSTN_VAL(x)        (((uint32_t)(x) << RF_PMU_RFFE_CTRL_RSTN_SHIFT) & RF_PMU_RFFE_CTRL_RSTN_MASK)
#define RF_PMU_REG_CTRL_RSTN_SHIFT          (21)
#define RF_PMU_REG_CTRL_RSTN_MASK           (0x1U << RF_PMU_REG_CTRL_RSTN_SHIFT)
#define RF_PMU_REG_CTRL_RSTN_VAL(x)         (((uint32_t)(x) << RF_PMU_REG_CTRL_RSTN_SHIFT) & RF_PMU_REG_CTRL_RSTN_MASK)
#define RF_PMU_RFFE_PLL_RSTN_SHIFT          (24)
#define RF_PMU_RFFE_PLL_RSTN_MASK           (0x1U << RF_PMU_RFFE_PLL_RSTN_SHIFT)
#define RF_PMU_RFFE_PLL_RSTN_VAL(x)         (((uint32_t)(x) << RF_PMU_RFFE_PLL_RSTN_SHIFT) & RF_PMU_RFFE_PLL_RSTN_MASK)
#define RF_PMU_REG_PLL_RSTN_SHIFT           (25)
#define RF_PMU_REG_PLL_RSTN_MASK            (0x1U << RF_PMU_REG_PLL_RSTN_SHIFT)
#define RF_PMU_REG_PLL_RSTN_VAL(x)          (((uint32_t)(x) << RF_PMU_REG_PLL_RSTN_SHIFT) & RF_PMU_REG_PLL_RSTN_MASK)
#define RF_PMU_RFFE_DFE_RSTN_SHIFT          (28)
#define RF_PMU_RFFE_DFE_RSTN_MASK           (0x1U << RF_PMU_RFFE_DFE_RSTN_SHIFT)
#define RF_PMU_RFFE_DFE_RSTN_VAL(x)         (((uint32_t)(x) << RF_PMU_RFFE_DFE_RSTN_SHIFT) & RF_PMU_RFFE_DFE_RSTN_MASK)
#define RF_PMU_REG_DFE_RSTN_SHIFT           (29)
#define RF_PMU_REG_DFE_RSTN_MASK            (0x1U << RF_PMU_REG_DFE_RSTN_SHIFT)
#define RF_PMU_REG_DFE_RSTN_VAL(x)          (((uint32_t)(x) << RF_PMU_REG_DFE_RSTN_SHIFT) & RF_PMU_REG_DFE_RSTN_MASK)

#define RF_PMU_PD_XTAL32K_SHIFT             (2)
#define RF_PMU_PD_XTAL32K_MASK              (0x1U << RF_PMU_PD_XTAL32K_SHIFT)
#define RF_PMU_PD_XTAL32K_VAL(x)            (((uint32_t)(x) << RF_PMU_PD_XTAL32K_SHIFT) & RF_PMU_PD_XTAL32K_MASK)

#define SLC_PD_PMU_D_MO_SHIFT               (0)
#define SLC_PD_PMU_D_MO_MASK                (0x1U << SLC_PD_PMU_D_MO_SHIFT)
#define SLC_PD_PMU_D_MO_VAL(x)              (((uint32_t)(x) << SLC_PD_PMU_D_MO_SHIFT) & SLC_PD_PMU_D_MO_MASK)
#define SLC_PD_PMU_32KOSC_MO_SHIFT          (1)
#define SLC_PD_PMU_32KOSC_MO_MASK           (0x1U << SLC_PD_PMU_32KOSC_MO_SHIFT)
#define SLC_PD_PMU_32KOSC_MO_VAL(x)         (((uint32_t)(x) << SLC_PD_PMU_32KOSC_MO_SHIFT) & SLC_PD_PMU_32KOSC_MO_MASK)
#define SLC_PD_PMU_BOR_SHIFT                (2)
#define SLC_PD_PMU_BOR_MASK                 (0x1U << SLC_PD_PMU_BOR_SHIFT)
#define SLC_PD_PMU_BOR_VAL(x)               (((uint32_t)(x) << SLC_PD_PMU_BOR_SHIFT) & SLC_PD_PMU_BOR_MASK)
#define SLC_PD_PMU_LVD_SHIFT                (3)
#define SLC_PD_PMU_LVD_MASK                 (0x1U << SLC_PD_PMU_LVD_SHIFT)
#define SLC_PD_PMU_LVD_VAL(x)               (((uint32_t)(x) << SLC_PD_PMU_LVD_SHIFT) & SLC_PD_PMU_LVD_MASK)
#define SLC_PD_PMU_RETBG_ILEAK_SHIFT        (4)
#define SLC_PD_PMU_RETBG_ILEAK_MASK         (0x1U << SLC_PD_PMU_RETBG_ILEAK_SHIFT)
#define SLC_PD_PMU_RETBG_ILEAK_VAL(x)       (((uint32_t)(x) << SLC_PD_PMU_RETBG_ILEAK_SHIFT) & SLC_PD_PMU_RETBG_ILEAK_MASK)

#define RF_CMU_TCXO_LDO_LVL_SHIFT           (0)
#define RF_CMU_TCXO_LDO_LVL_MASK            (0x7U << RF_CMU_TCXO_LDO_LVL_SHIFT)
#define RF_CMU_TCXO_LDO_LVL_VAL(x)          (((uint32_t)(x) << RF_CMU_TCXO_LDO_LVL_SHIFT) & RF_CMU_TCXO_LDO_LVL_MASK)
#define RF_CMU_TCXO_OCP_EN_SHIFT            (4)
#define RF_CMU_TCXO_OCP_EN_MASK             (0x1U << RF_CMU_TCXO_OCP_EN_SHIFT)
#define RF_CMU_TCXO_OCP_EN_VAL(x)           (((uint32_t)(x) << RF_CMU_TCXO_OCP_EN_SHIFT) & RF_CMU_TCXO_OCP_EN_MASK)
#define RF_CMU_TCXO_BYPASS_SHIFT            (5)
#define RF_CMU_TCXO_BYPASS_MASK             (0x1U << RF_CMU_TCXO_BYPASS_SHIFT)
#define RF_CMU_TCXO_BYPASS_VAL(x)           (((uint32_t)(x) << RF_CMU_TCXO_BYPASS_SHIFT) & RF_CMU_TCXO_BYPASS_MASK)

#define SLC_CMU_OSC32K_FREQ_CTRIM_SHIFT     (0)
#define SLC_CMU_OSC32K_FREQ_CTRIM_MASK      (0xFFU << SLC_CMU_OSC32K_FREQ_CTRIM_SHIFT)
#define SLC_CMU_OSC32K_FREQ_CTRIM_VAL(x)    (((uint32_t)(x) << SLC_CMU_OSC32K_FREQ_CTRIM_SHIFT) & SLC_CMU_OSC32K_FREQ_CTRIM_MASK)
#define SLC_CMU_OSC32K_FREQ_RTRIM_SHIFT     (8)
#define SLC_CMU_OSC32K_FREQ_RTRIM_MASK      (0xFFU << SLC_CMU_OSC32K_FREQ_RTRIM_SHIFT)
#define SLC_CMU_OSC32K_FREQ_RTRIM_VAL(x)    (((uint32_t)(x) << SLC_CMU_OSC32K_FREQ_RTRIM_SHIFT) & SLC_CMU_OSC32K_FREQ_RTRIM_MASK)

#define SLC_CMU_OSC50M_FREQ_CTUNE_SHIFT     (0)
#define SLC_CMU_OSC50M_FREQ_CTUNE_MASK      (0x3FU << SLC_CMU_OSC50M_FREQ_CTUNE_SHIFT)
#define SLC_CMU_OSC50M_FREQ_CTUNE_VAL(x)    (((uint32_t)(x) << SLC_CMU_OSC50M_FREQ_CTUNE_SHIFT) & SLC_CMU_OSC50M_FREQ_CTUNE_MASK)
#define SLC_CMU_OSC50M_FREQ_RTUNE_SHIFT     (8)
#define SLC_CMU_OSC50M_FREQ_RTUNE_MASK      (0x3FU << SLC_CMU_OSC50M_FREQ_RTUNE_SHIFT)
#define SLC_CMU_OSC50M_FREQ_RTUNE_VAL(x)    (((uint32_t)(x) << SLC_CMU_OSC50M_FREQ_RTUNE_SHIFT) & SLC_CMU_OSC50M_FREQ_RTUNE_MASK)

#define SLC_DCDC_OSC_CAPTRIM_SHIFT          (0)
#define SLC_DCDC_OSC_CAPTRIM_MASK           (0x3FU << SLC_DCDC_OSC_CAPTRIM_SHIFT)
#define SLC_DCDC_OSC_CAPTRIM_VAL(x)         (((uint32_t)(x) << SLC_DCDC_OSC_CAPTRIM_SHIFT) & SLC_DCDC_OSC_CAPTRIM_MASK)

#define SLC_PMU_IOUT_TUNE_TRIM_SHIFT        (0)
#define SLC_PMU_IOUT_TUNE_TRIM_MASK         (0xFU << SLC_PMU_IOUT_TUNE_TRIM_SHIFT)
#define SLC_PMU_IOUT_TUNE_TRIM_VAL(x)       (((uint32_t)(x) << SLC_PMU_IOUT_TUNE_TRIM_SHIFT) & SLC_PMU_IOUT_TUNE_TRIM_MASK)
#define SLC_PMU_IOUT_PTAT_TRIM_SHIFT        (4)
#define SLC_PMU_IOUT_PTAT_TRIM_MASK         (0x1FU << SLC_PMU_IOUT_PTAT_TRIM_SHIFT)
#define SLC_PMU_IOUT_PTAT_TRIM_VAL(x)       (((uint32_t)(x) << SLC_PMU_IOUT_PTAT_TRIM_SHIFT) & SLC_PMU_IOUT_PTAT_TRIM_MASK)
#define SLC_PMU_ICAL_PATH_SHIFT             (9)
#define SLC_PMU_ICAL_PATH_MASK              (0x1U << SLC_PMU_ICAL_PATH_SHIFT)
#define SLC_PMU_ICAL_PATH_VAL(x)            (((uint32_t)(x) << SLC_PMU_ICAL_PATH_SHIFT) & SLC_PMU_ICAL_PATH_MASK)
#define SLC_PMU_CNTL_RET_LDO_SHIFT          (10)
#define SLC_PMU_CNTL_RET_LDO_MASK           (0x7U << SLC_PMU_CNTL_RET_LDO_SHIFT)
#define SLC_PMU_CNTL_RET_LDO_VAL(x)         (((uint32_t)(x) << SLC_PMU_CNTL_RET_LDO_SHIFT) & SLC_PMU_CNTL_RET_LDO_MASK)
#define SLC_PMU_CNTL_V1P1_LDO_SHIFT         (13)
#define SLC_PMU_CNTL_V1P1_LDO_MASK          (0x7U << SLC_PMU_CNTL_V1P1_LDO_SHIFT)
#define SLC_PMU_CNTL_V1P1_LDO_VAL(x)        (((uint32_t)(x) << SLC_PMU_CNTL_V1P1_LDO_SHIFT) & SLC_PMU_CNTL_V1P1_LDO_MASK)
#define SLC_PMU_LVD_CRVT_SHIFT              (16)
#define SLC_PMU_LVD_CRVT_MASK               (0xFU << SLC_PMU_LVD_CRVT_SHIFT)
#define SLC_PMU_LVD_CRVT_VAL(x)             (((uint32_t)(x) << SLC_PMU_LVD_CRVT_SHIFT) & SLC_PMU_LVD_CRVT_MASK)
#define SLC_PMU_LVD_OUT_POL_SHIFT           (31)
#define SLC_PMU_LVD_OUT_POL_MASK            (0x1U << SLC_PMU_LVD_OUT_POL_SHIFT)
#define SLC_PMU_LVD_OUT_POL_VAL(x)          (((uint32_t)(x) << SLC_PMU_LVD_OUT_POL_SHIFT) & SLC_PMU_LVD_OUT_POL_MASK)

#define SLC_PMU_RESERVE_SHIFT               (0)
#define SLC_PMU_RESERVE_MASK                (0xFU << SLC_PMU_RESERVE_SHIFT)
#define SLC_PMU_RESERVE_VAL(x)              (((uint32_t)(x) << SLC_PMU_RESERVE_SHIFT) & SLC_PMU_RESERVE_MASK)

#define SLC_RC_CALIB_CNT1_SHIFT             (0)
#define SLC_RC_CALIB_CNT1_MASK              (0x3FFU << SLC_RC_CALIB_CNT1_SHIFT)
#define SLC_RC_CALIB_CNT1_VAL(x)            (((uint32_t)(x) << SLC_RC_CALIB_CNT1_SHIFT) & SLC_RC_CALIB_CNT1_MASK)
#define SLC_RC_CALIB_CNT2_SHIFT             (12)
#define SLC_RC_CALIB_CNT2_MASK              (0x3FFU << SLC_RC_CALIB_CNT2_SHIFT)
#define SLC_RC_CALIB_CNT2_VAL(x)            (((uint32_t)(x) << SLC_RC_CALIB_CNT2_SHIFT) & SLC_RC_CALIB_CNT2_MASK)

#define SLC_CMU_FDOUB_CTUNE_SHIFT           (0)
#define SLC_CMU_FDOUB_CTUNE_MASK            (0xFU << SLC_CMU_FDOUB_CTUNE_SHIFT)
#define SLC_CMU_FDOUB_CTUNE_VAL(x)          (((uint32_t)(x) << SLC_CMU_FDOUB_CTUNE_SHIFT) & SLC_CMU_FDOUB_CTUNE_MASK)

typedef struct
{
    __IOM uint32_t RF_MODE_CTRL;     // 0x00
    __IOM uint32_t RF_CALI_CTRL;     // 0x04
    __IOM uint32_t CAL_DCDC_1M_CTRL; // 0x08
    __IOM uint32_t CAL_DCDC_1M_INIT; // 0x0C
    __IOM uint32_t CAL_DCDC_1M_CNT;  // 0x10
    __IOM uint32_t CAL_DCDC_1M_TGT;  // 0x14
    __IOM uint32_t CAL_DCDC_1M_RPT;  // 0x18
    __IOM uint32_t CAL_RC_32K_CTRL;  // 0x1C
    __IOM uint32_t CAL_RC_32K_INIT;  // 0x20
    __IOM uint32_t CAL_RC_32K_CNT;   // 0x24
    __IOM uint32_t CAL_RC_32K_TGT;   // 0x28
    __IOM uint32_t CAL_RC_32K_RPT;   // 0x2C
    __IOM uint32_t CAL_RC_50M_CTRL;  // 0x30
    __IOM uint32_t CAL_RC_50M_INIT;  // 0x34
    __IOM uint32_t CAL_RC_50M_CNT;   // 0x38
    __IOM uint32_t CAL_RC_50M_TGT;   // 0x3C
    __IOM uint32_t CAL_RC_50M_RPT;   // 0x40
    __IOM uint32_t CAL_RC_CTRL;      // 0x44
    __IOM uint32_t CAL_RC_RPT;       // 0x48
    __IOM uint32_t TXABB_PD_CTRL;    // 0x4C
    __IOM uint32_t TXRF_PD_CTRL;     // 0x50
    __IOM uint32_t RXABB_PD_CTRL;    // 0x54
    __IOM uint32_t RXRF_PD_CTRL;     // 0x58
    __IOM uint32_t GPADC_PD_CTRL;    // 0x5C
    __IOM uint32_t CLK_GATES;        // 0x60
    __IOM uint32_t RST_CTRL;         // 0x64
    __IOM uint32_t TX_RAMPING_CTRL;  // 0x68
    __IOM uint32_t TXABB_DAC_CTRL;   // 0x6C
    __IOM uint32_t TXABB_LPF_CTRL;   // 0x70
    __IOM uint32_t TXABB_LPF_TRIM;   // 0x74
    __IOM uint32_t TXRF_LDO_CTRL;    // 0x78
    __IOM uint32_t TXRF_UPC_CTRL;    // 0x7C
    __IOM uint32_t TXRF_PA_PPA_CTRL; // 0x80
    __IOM uint32_t TXRF_PDET_CTRL;   // 0x84
    __IOM uint32_t TXRF_TSENSOR_CTRL;// 0x88
    __IOM uint32_t TX_RESERVE;       // 0x8C
    __IOM uint32_t RXABB_LDO_CTRL;   // 0x90
    __IOM uint32_t RXABB_CBPF_CTRL;  // 0x94
    __IOM uint32_t RXABB_DCOC_CTRL;  // 0x98
    __IOM uint32_t RXABB_RCCAL_CTRL; // 0x9C
    __IOM uint32_t RXABB_ADC_CTRL;   // 0xA0
    __IOM uint32_t RXABB_RSSI_CTRL;  // 0xA4
    __IOM uint32_t RXABB_OUT;        // 0xA8
    __IOM uint32_t RXABB_ATB_CTRL;   // 0xAC
    __IOM uint32_t RXRF_LNA_ATT_CTRL;// 0xB0
    __IOM uint32_t RXRF_MIX_TIA_CTRL;// 0xB4
    __IOM uint32_t RX_RESERVE;       // 0xB8
    __IOM uint32_t TRX_SW_CTRL;      // 0xBC
    __IOM uint32_t GPADC_CTRL;       // 0xC0
    __IOM uint32_t RF_GPIO_IE_CTRL;  // 0xC4
    __IOM uint32_t RF_GPIO_OEN_CTRL; // 0xC8
    __IOM uint32_t RF_GPIO_REN_CTRL; // 0xCC
    __IOM uint32_t ATB_TRXABB_CTRL;  // 0xD0
    __IOM uint32_t ATB_TRXRF_CTRL;   // 0xD4
    __IOM uint32_t RFFE_DBG_CTRL;    // 0xD8
} rf_ctrl_handle_t;

#define RFCTRL_PD_I_TXDAC_MO_SHIFT          (0)
#define RFCTRL_PD_I_TXDAC_MO_MASK           (0x1U << RFCTRL_PD_I_TXDAC_MO_SHIFT)
#define RFCTRL_PD_I_TXDAC_MO_VAL(x)         (((uint32_t)(x) << RFCTRL_PD_I_TXDAC_MO_SHIFT) & RFCTRL_PD_I_TXDAC_MO_MASK)
#define RFCTRL_PD_Q_TXDAC_MO_SHIFT          (1)
#define RFCTRL_PD_Q_TXDAC_MO_MASK           (0x1U << RFCTRL_PD_Q_TXDAC_MO_SHIFT)
#define RFCTRL_PD_Q_TXDAC_MO_VAL(x)         (((uint32_t)(x) << RFCTRL_PD_Q_TXDAC_MO_SHIFT) & RFCTRL_PD_Q_TXDAC_MO_MASK)
#define RFCTRL_PD_TXDAC_IBIAS_I_MO_SHIFT    (2)
#define RFCTRL_PD_TXDAC_IBIAS_I_MO_MASK     (0x1U << RFCTRL_PD_TXDAC_IBIAS_I_MO_SHIFT)
#define RFCTRL_PD_TXDAC_IBIAS_I_MO_VAL(x)   (((uint32_t)(x) << RFCTRL_PD_TXDAC_IBIAS_I_MO_SHIFT) & RFCTRL_PD_TXDAC_IBIAS_I_MO_MASK)
#define RFCTRL_PD_TXDAC_IBIAS_Q_MO_SHIFT    (3)
#define RFCTRL_PD_TXDAC_IBIAS_Q_MO_MASK     (0x1U << RFCTRL_PD_TXDAC_IBIAS_Q_MO_SHIFT)
#define RFCTRL_PD_TXDAC_IBIAS_Q_MO_VAL(x)   (((uint32_t)(x) << RFCTRL_PD_TXDAC_IBIAS_Q_MO_SHIFT) & RFCTRL_PD_TXDAC_IBIAS_Q_MO_MASK)
#define RFCTRL_PD_TXLPF_MO_SHIFT            (4)
#define RFCTRL_PD_TXLPF_MO_MASK             (0x1U << RFCTRL_PD_TXLPF_MO_SHIFT)
#define RFCTRL_PD_TXLPF_MO_VAL(x)           (((uint32_t)(x) << RFCTRL_PD_TXLPF_MO_SHIFT) & RFCTRL_PD_TXLPF_MO_MASK)
#define RFCTRL_PD_TXLPF_IBIAS_MO_SHIFT      (5)
#define RFCTRL_PD_TXLPF_IBIAS_MO_MASK       (0x1U << RFCTRL_PD_TXLPF_IBIAS_MO_SHIFT)
#define RFCTRL_PD_TXLPF_IBIAS_MO_VAL(x)     (((uint32_t)(x) << RFCTRL_PD_TXLPF_IBIAS_MO_SHIFT) & RFCTRL_PD_TXLPF_IBIAS_MO_MASK)
#define RFCTRL_PD_TXLPF_TIA_MO_SHIFT        (6)
#define RFCTRL_PD_TXLPF_TIA_MO_MASK         (0x1U << RFCTRL_PD_TXLPF_TIA_MO_SHIFT)
#define RFCTRL_PD_TXLPF_TIA_MO_VAL(x)       (((uint32_t)(x) << RFCTRL_PD_TXLPF_TIA_MO_SHIFT) & RFCTRL_PD_TXLPF_TIA_MO_MASK)
#define RFCTRL_PD_I_TXDAC_ME_SHIFT          (16)
#define RFCTRL_PD_I_TXDAC_ME_MASK           (0x1U << RFCTRL_PD_I_TXDAC_ME_SHIFT)
#define RFCTRL_PD_I_TXDAC_ME_VAL(x)         (((uint32_t)(x) << RFCTRL_PD_I_TXDAC_ME_SHIFT) & RFCTRL_PD_I_TXDAC_ME_MASK)
#define RFCTRL_PD_Q_TXDAC_ME_SHIFT          (17)
#define RFCTRL_PD_Q_TXDAC_ME_MASK           (0x1U << RFCTRL_PD_Q_TXDAC_ME_SHIFT)
#define RFCTRL_PD_Q_TXDAC_ME_VAL(x)         (((uint32_t)(x) << RFCTRL_PD_Q_TXDAC_ME_SHIFT) & RFCTRL_PD_Q_TXDAC_ME_MASK)
#define RFCTRL_PD_TXDAC_IBIAS_I_ME_SHIFT    (18)
#define RFCTRL_PD_TXDAC_IBIAS_I_ME_MASK     (0x1U << RFCTRL_PD_TXDAC_IBIAS_I_ME_SHIFT)
#define RFCTRL_PD_TXDAC_IBIAS_I_ME_VAL(x)   (((uint32_t)(x) << RFCTRL_PD_TXDAC_IBIAS_I_ME_SHIFT) & RFCTRL_PD_TXDAC_IBIAS_I_ME_MASK)
#define RFCTRL_PD_TXDAC_IBIAS_Q_ME_SHIFT    (19)
#define RFCTRL_PD_TXDAC_IBIAS_Q_ME_MASK     (0x1U << RFCTRL_PD_TXDAC_IBIAS_Q_ME_SHIFT)
#define RFCTRL_PD_TXDAC_IBIAS_Q_ME_VAL(x)   (((uint32_t)(x) << RFCTRL_PD_TXDAC_IBIAS_Q_ME_SHIFT) & RFCTRL_PD_TXDAC_IBIAS_Q_ME_MASK)
#define RFCTRL_PD_TXLPF_ME_SHIFT            (20)
#define RFCTRL_PD_TXLPF_ME_MASK             (0x1U << RFCTRL_PD_TXLPF_ME_SHIFT)
#define RFCTRL_PD_TXLPF_ME_VAL(x)           (((uint32_t)(x) << RFCTRL_PD_TXLPF_ME_SHIFT) & RFCTRL_PD_TXLPF_ME_MASK)
#define RFCTRL_PD_TXLPF_IBIAS_ME_SHIFT      (21)
#define RFCTRL_PD_TXLPF_IBIAS_ME_MASK       (0x1U << RFCTRL_PD_TXLPF_IBIAS_ME_SHIFT)
#define RFCTRL_PD_TXLPF_IBIAS_ME_VAL(x)     (((uint32_t)(x) << RFCTRL_PD_TXLPF_IBIAS_ME_SHIFT) & RFCTRL_PD_TXLPF_IBIAS_ME_MASK)
#define RFCTRL_PD_TXLPF_TIA_ME_SHIFT        (22)
#define RFCTRL_PD_TXLPF_TIA_ME_MASK         (0x1U << RFCTRL_PD_TXLPF_TIA_ME_SHIFT)
#define RFCTRL_PD_TXLPF_TIA_ME_VAL(x)       (((uint32_t)(x) << RFCTRL_PD_TXLPF_TIA_ME_SHIFT) & RFCTRL_PD_TXLPF_TIA_ME_MASK)

#define RFCTRL_TXDAC_RSTN_MO_SHIFT          (0)
#define RFCTRL_TXDAC_RSTN_MO_MASK           (0x1U << RFCTRL_TXDAC_RSTN_MO_SHIFT)
#define RFCTRL_TXDAC_RSTN_MO_VAL(x)         (((uint32_t)(x) << RFCTRL_TXDAC_RSTN_MO_SHIFT) & RFCTRL_TXDAC_RSTN_MO_MASK)
#define RFCTRL_TXDAC_CLK_PHASE_SHIFT        (1)
#define RFCTRL_TXDAC_CLK_PHASE_MASK         (0x1U << RFCTRL_TXDAC_CLK_PHASE_SHIFT)
#define RFCTRL_TXDAC_CLK_PHASE_VAL(x)       (((uint32_t)(x) << RFCTRL_TXDAC_CLK_PHASE_SHIFT) & RFCTRL_TXDAC_CLK_PHASE_MASK)
#define RFCTRL_TXDAC_GAIN_SHIFT             (4)
#define RFCTRL_TXDAC_GAIN_MASK              (0x3U << RFCTRL_TXDAC_GAIN_SHIFT)
#define RFCTRL_TXDAC_GAIN_VAL(x)            (((uint32_t)(x) << RFCTRL_TXDAC_GAIN_SHIFT) & RFCTRL_TXDAC_GAIN_MASK)
#define RFCTRL_TXDAC_RSTN_ME_SHIFT          (16)
#define RFCTRL_TXDAC_RSTN_ME_MASK           (0x1U << RFCTRL_TXDAC_RSTN_ME_SHIFT)
#define RFCTRL_TXDAC_RSTN_ME_VAL(x)         (((uint32_t)(x) << RFCTRL_TXDAC_RSTN_ME_SHIFT) & RFCTRL_TXDAC_RSTN_ME_MASK)

#define RFCTRL_TXLPF_BWMODE_SHIFT           (0)
#define RFCTRL_TXLPF_BWMODE_MASK            (0x7U << RFCTRL_TXLPF_BWMODE_SHIFT)
#define RFCTRL_TXLPF_BWMODE_VAL(x)          (((uint32_t)(x) << RFCTRL_TXLPF_BWMODE_SHIFT) & RFCTRL_TXLPF_BWMODE_MASK)
#define RFCTRL_TXLPF_GAIN_SHIFT             (4)
#define RFCTRL_TXLPF_GAIN_MASK              (0x7U << RFCTRL_TXLPF_GAIN_SHIFT)
#define RFCTRL_TXLPF_GAIN_VAL(x)            (((uint32_t)(x) << RFCTRL_TXLPF_GAIN_SHIFT) & RFCTRL_TXLPF_GAIN_MASK)

#define SLC_RFCTRL_PPA_CNTL_LDO_SHIFT       (0)
#define SLC_RFCTRL_PPA_CNTL_LDO_MASK        (0xFU << SLC_RFCTRL_PPA_CNTL_LDO_SHIFT)
#define SLC_RFCTRL_PPA_CNTL_LDO_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_PPA_CNTL_LDO_SHIFT) & SLC_RFCTRL_PPA_CNTL_LDO_MASK)
#define SLC_RFCTRL_PA_CNTL_LDO_MO_SHIFT     (4)
#define SLC_RFCTRL_PA_CNTL_LDO_MO_MASK      (0xFFU << SLC_RFCTRL_PA_CNTL_LDO_MO_SHIFT)
#define SLC_RFCTRL_PA_CNTL_LDO_MO_VAL(x)    (((uint32_t)(x) << SLC_RFCTRL_PA_CNTL_LDO_MO_SHIFT) & SLC_RFCTRL_PA_CNTL_LDO_MO_MASK)
#define SLC_RFCTRL_PA_CNTL_LDO_ME_SHIFT     (20)
#define SLC_RFCTRL_PA_CNTL_LDO_ME_MASK      (0xFU << SLC_RFCTRL_PA_CNTL_LDO_ME_SHIFT)
#define SLC_RFCTRL_PA_CNTL_LDO_ME_VAL(x)    (((uint32_t)(x) << SLC_RFCTRL_PA_CNTL_LDO_ME_SHIFT) & SLC_RFCTRL_PA_CNTL_LDO_ME_MASK)

#define SLC_RFCTRL_PD_RXABB_LDO_MO_SHIFT    (0)
#define SLC_RFCTRL_PD_RXABB_LDO_MO_MASK     (0x1U << SLC_RFCTRL_PD_RXABB_LDO_MO_SHIFT)
#define SLC_RFCTRL_PD_RXABB_LDO_MO_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_PD_RXABB_LDO_MO_SHIFT) & SLC_RFCTRL_PD_RXABB_LDO_MO_MASK)
#define SLC_RFCTRL_RXABB_LDO_FSO_MO_SHIFT   (1)
#define SLC_RFCTRL_RXABB_LDO_FSO_MO_MASK    (0x1U << SLC_RFCTRL_RXABB_LDO_FSO_MO_SHIFT)
#define SLC_RFCTRL_RXABB_LDO_FSO_MO_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_RXABB_LDO_FSO_MO_SHIFT) & SLC_RFCTRL_RXABB_LDO_FSO_MO_MASK)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_MO_SHIFT (2)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_MO_MASK  (0x3U << SLC_RFCTRL_RXABB_LDO_RLOAD_MO_SHIFT)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXABB_LDO_RLOAD_MO_SHIFT) & SLC_RFCTRL_RXABB_LDO_RLOAD_MO_MASK)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_SHIFT (4)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_MASK  (0x1U << SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_SHIFT)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_SHIFT) & SLC_RFCTRL_PD_I_IBIAS_CBPF_MO_MASK)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_SHIFT (5)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_MASK  (0x1U << SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_SHIFT)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_SHIFT) & SLC_RFCTRL_PD_Q_IBIAS_CBPF_MO_MASK)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_MO_SHIFT (6)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_MO_MASK  (0x1U << SLC_RFCTRL_PD_I_RXABB_CBPF_MO_SHIFT)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_I_RXABB_CBPF_MO_SHIFT) & SLC_RFCTRL_PD_I_RXABB_CBPF_MO_MASK)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_SHIFT (7)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_MASK  (0x1U << SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_SHIFT)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_SHIFT) & SLC_RFCTRL_PD_Q_RXABB_CBPF_MO_MASK)
#define SLC_RFCTRL_PD_RXADC_ANALDO_MO_SHIFT (8)
#define SLC_RFCTRL_PD_RXADC_ANALDO_MO_MASK  (0x1U << SLC_RFCTRL_PD_RXADC_ANALDO_MO_SHIFT)
#define SLC_RFCTRL_PD_RXADC_ANALDO_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_ANALDO_MO_SHIFT) & SLC_RFCTRL_PD_RXADC_ANALDO_MO_MASK)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_MO_SHIFT (9)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_MO_MASK  (0x1U << SLC_RFCTRL_RXADC_ANALDO_FSO_MO_SHIFT)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXADC_ANALDO_FSO_MO_SHIFT) & SLC_RFCTRL_RXADC_ANALDO_FSO_MO_MASK)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_MO_SHIFT (10)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_MO_MASK  (0x1U << SLC_RFCTRL_PD_RXADC_DIGLDO_MO_SHIFT)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_DIGLDO_MO_SHIFT) & SLC_RFCTRL_PD_RXADC_DIGLDO_MO_MASK)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_SHIFT (11)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_MASK  (0x1U << SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_SHIFT)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_SHIFT) & SLC_RFCTRL_RXADC_DIGLDO_FSO_MO_MASK)
#define SLC_RFCTRL_PD_RXADC_COM_MO_SHIFT    (12)
#define SLC_RFCTRL_PD_RXADC_COM_MO_MASK     (0x1U << SLC_RFCTRL_PD_RXADC_COM_MO_SHIFT)
#define SLC_RFCTRL_PD_RXADC_COM_MO_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_COM_MO_SHIFT) & SLC_RFCTRL_PD_RXADC_COM_MO_MASK)
#define SLC_RFCTRL_PD_RXADC_MO_SHIFT        (13)
#define SLC_RFCTRL_PD_RXADC_MO_MASK         (0x1U << SLC_RFCTRL_PD_RXADC_MO_SHIFT)
#define SLC_RFCTRL_PD_RXADC_MO_VAL(x)       (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_MO_SHIFT) & SLC_RFCTRL_PD_RXADC_MO_MASK)
#define SLC_RFCTRL_PD_RXRSSI_MO_SHIFT       (14)
#define SLC_RFCTRL_PD_RXRSSI_MO_MASK        (0x1U << SLC_RFCTRL_PD_RXRSSI_MO_SHIFT)
#define SLC_RFCTRL_PD_RXRSSI_MO_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_PD_RXRSSI_MO_SHIFT) & SLC_RFCTRL_PD_RXRSSI_MO_MASK)
#define SLC_RFCTRL_PD_RXABB_LDO_ME_SHIFT    (16)
#define SLC_RFCTRL_PD_RXABB_LDO_ME_MASK     (0x1U << SLC_RFCTRL_PD_RXABB_LDO_ME_SHIFT)
#define SLC_RFCTRL_PD_RXABB_LDO_ME_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_PD_RXABB_LDO_ME_SHIFT) & SLC_RFCTRL_PD_RXABB_LDO_ME_MASK)
#define SLC_RFCTRL_RXABB_LDO_FSO_ME_SHIFT   (17)
#define SLC_RFCTRL_RXABB_LDO_FSO_ME_MASK    (0x1U << SLC_RFCTRL_RXABB_LDO_FSO_ME_SHIFT)
#define SLC_RFCTRL_RXABB_LDO_FSO_ME_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_RXABB_LDO_FSO_ME_SHIFT) & SLC_RFCTRL_RXABB_LDO_FSO_ME_MASK)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_ME_SHIFT (18)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_ME_MASK  (0x1U << SLC_RFCTRL_RXABB_LDO_RLOAD_ME_SHIFT)
#define SLC_RFCTRL_RXABB_LDO_RLOAD_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXABB_LDO_RLOAD_ME_SHIFT) & SLC_RFCTRL_RXABB_LDO_RLOAD_ME_MASK)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_SHIFT (20)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_MASK  (0x1U << SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_SHIFT)
#define SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_SHIFT) & SLC_RFCTRL_PD_I_IBIAS_CBPF_ME_MASK)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_SHIFT (21)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_MASK  (0x1U << SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_SHIFT)
#define SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_SHIFT) & SLC_RFCTRL_PD_Q_IBIAS_CBPF_ME_MASK)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_ME_SHIFT (22)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_ME_MASK  (0x1U << SLC_RFCTRL_PD_I_RXABB_CBPF_ME_SHIFT)
#define SLC_RFCTRL_PD_I_RXABB_CBPF_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_I_RXABB_CBPF_ME_SHIFT) & SLC_RFCTRL_PD_I_RXABB_CBPF_ME_MASK)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_SHIFT (23)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_MASK  (0x1U << SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_SHIFT)
#define SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_SHIFT) & SLC_RFCTRL_PD_Q_RXABB_CBPF_ME_MASK)
#define SLC_RFCTRL_PD_RXADC_ANALDO_ME_SHIFT (24)
#define SLC_RFCTRL_PD_RXADC_ANALDO_ME_MASK  (0x1U << SLC_RFCTRL_PD_RXADC_ANALDO_ME_SHIFT)
#define SLC_RFCTRL_PD_RXADC_ANALDO_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_ANALDO_ME_SHIFT) & SLC_RFCTRL_PD_RXADC_ANALDO_ME_MASK)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_ME_SHIFT (25)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_ME_MASK  (0x1U << SLC_RFCTRL_RXADC_ANALDO_FSO_ME_SHIFT)
#define SLC_RFCTRL_RXADC_ANALDO_FSO_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXADC_ANALDO_FSO_ME_SHIFT) & SLC_RFCTRL_RXADC_ANALDO_FSO_ME_MASK)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_ME_SHIFT (26)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_ME_MASK  (0x1U << SLC_RFCTRL_PD_RXADC_DIGLDO_ME_SHIFT)
#define SLC_RFCTRL_PD_RXADC_DIGLDO_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_DIGLDO_ME_SHIFT) & SLC_RFCTRL_PD_RXADC_DIGLDO_ME_MASK)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_SHIFT (27)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_MASK  (0x1U << SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_SHIFT)
#define SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_SHIFT) & SLC_RFCTRL_RXADC_DIGLDO_FSO_ME_MASK)
#define SLC_RFCTRL_PD_RXADC_COM_ME_SHIFT    (28)
#define SLC_RFCTRL_PD_RXADC_COM_ME_MASK     (0x1U << SLC_RFCTRL_PD_RXADC_COM_ME_SHIFT)
#define SLC_RFCTRL_PD_RXADC_COM_ME_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_COM_ME_SHIFT) & SLC_RFCTRL_PD_RXADC_COM_ME_MASK)
#define SLC_RFCTRL_PD_RXADC_ME_SHIFT        (29)
#define SLC_RFCTRL_PD_RXADC_ME_MASK         (0x1U << SLC_RFCTRL_PD_RXADC_ME_SHIFT)
#define SLC_RFCTRL_PD_RXADC_ME_VAL(x)       (((uint32_t)(x) << SLC_RFCTRL_PD_RXADC_ME_SHIFT) & SLC_RFCTRL_PD_RXADC_ME_MASK)
#define SLC_RFCTRL_PD_RXRSSI_ME_SHIFT       (30)
#define SLC_RFCTRL_PD_RXRSSI_ME_MASK        (0x1U << SLC_RFCTRL_PD_RXRSSI_ME_SHIFT)
#define SLC_RFCTRL_PD_RXRSSI_ME_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_PD_RXRSSI_ME_SHIFT) & SLC_RFCTRL_PD_RXRSSI_ME_MASK)

#define SLC_RFCTRL_TX_UPC_HRM_II_TRIM_SHIFT (28)
#define SLC_RFCTRL_TX_UPC_HRM_II_TRIM_MASK  (0x7U << SLC_RFCTRL_TX_UPC_HRM_II_TRIM_SHIFT)
#define SLC_RFCTRL_TX_UPC_HRM_II_TRIM_VAL(x) ((((uint32_t)(x) << SLC_RFCTRL_TX_UPC_HRM_II_TRIM_SHIFT) & SLC_RFCTRL_TX_UPC_HRM_II_TRIM_MASK))
#define SLC_RFCTRL_TX_UPC_HRM_I_TRIM_SHIFT  (24)
#define SLC_RFCTRL_TX_UPC_HRM_I_TRIM_MASK   (0x7U << SLC_RFCTRL_TX_UPC_HRM_I_TRIM_SHIFT)
#define SLC_RFCTRL_TX_UPC_HRM_I_TRIM_VAL(x) ((((uint32_t)(x) << SLC_RFCTRL_TX_UPC_HRM_I_TRIM_SHIFT) & SLC_RFCTRL_TX_UPC_HRM_I_TRIM_MASK))
#define SLC_RFCTRL_TX_UPC_IBIAS_TRIM_SHIFT  (12)
#define SLC_RFCTRL_TX_UPC_IBIAS_TRIM_MASK   (0x7U << SLC_RFCTRL_TX_UPC_IBIAS_TRIM_SHIFT)
#define SLC_RFCTRL_TX_UPC_IBIAS_TRIM_VAL(x) ((((uint32_t)(x) << SLC_RFCTRL_TX_UPC_IBIAS_TRIM_SHIFT) & SLC_RFCTRL_TX_UPC_IBIAS_TRIM_MASK))
#define SLC_RFCTRL_TX_BAND_SEL_SHIFT        (2)
#define SLC_RFCTRL_TX_BAND_SEL_MASK         (0x3U << SLC_RFCTRL_TX_BAND_SEL_SHIFT)
#define SLC_RFCTRL_TX_BAND_SEL_VAL(x)       (((uint32_t)(x) << SLC_RFCTRL_TX_BAND_SEL_SHIFT) & SLC_RFCTRL_TX_BAND_SEL_MASK)

#define SLC_RFCTRL_TX_RAMP_STEP_SHIFT       (0)
#define SLC_RFCTRL_TX_RAMP_STEP_MASK        (0xFFU << SLC_RFCTRL_TX_RAMP_STEP_SHIFT)
#define SLC_RFCTRL_TX_RAMP_STEP_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_TX_RAMP_STEP_SHIFT) & SLC_RFCTRL_TX_RAMP_STEP_MASK)
#define SLC_RFCTRL_TX_RAMP_CYCLE_SHIFT      (8)
#define SLC_RFCTRL_TX_RAMP_CYCLE_MASK       (0xFFU << SLC_RFCTRL_TX_RAMP_CYCLE_SHIFT)
#define SLC_RFCTRL_TX_RAMP_CYCLE_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_TX_RAMP_CYCLE_SHIFT) & SLC_RFCTRL_TX_RAMP_CYCLE_MASK)
#define SLC_RFCTRL_DFE_DELAY_SHIFT          (20)
#define SLC_RFCTRL_DFE_DELAY_MASK           (0x3FFU << SLC_RFCTRL_DFE_DELAY_SHIFT)
#define SLC_RFCTRL_DFE_DELAY_VAL(x)         (((uint32_t)(x) << SLC_RFCTRL_DFE_DELAY_SHIFT) & SLC_RFCTRL_DFE_DELAY_MASK)

#define SLC_RFCTRL_TX_PA_VB_CS_P_SHIFT      (12)
#define SLC_RFCTRL_TX_PA_VB_CS_P_MASK       (0x7U << SLC_RFCTRL_TX_PA_VB_CS_P_SHIFT)
#define SLC_RFCTRL_TX_PA_VB_CS_P_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_TX_PA_VB_CS_P_SHIFT) & SLC_RFCTRL_TX_PA_VB_CS_P_MASK)

#define SLC_RFCTRL_TX_EN_MO_SHIFT           (0)
#define SLC_RFCTRL_TX_EN_MO_MASK            (0x1U << SLC_RFCTRL_TX_EN_MO_SHIFT)
#define SLC_RFCTRL_TX_EN_MO_VAL(x)          (((uint32_t)(x) << SLC_RFCTRL_TX_EN_MO_SHIFT) & SLC_RFCTRL_TX_EN_MO_MASK)
#define SLC_RFCTRL_RX_EN_MO_SHIFT           (1)
#define SLC_RFCTRL_RX_EN_MO_MASK            (0x1U << SLC_RFCTRL_RX_EN_MO_SHIFT)
#define SLC_RFCTRL_RX_EN_MO_VAL(x)          (((uint32_t)(x) << SLC_RFCTRL_RX_EN_MO_SHIFT) & SLC_RFCTRL_RX_EN_MO_MASK)
#define SLC_RFCTRL_TX_CAL_EN_SHIFT          (2)
#define SLC_RFCTRL_TX_CAL_EN_MASK           (0x1U << SLC_RFCTRL_TX_CAL_EN_SHIFT)
#define SLC_RFCTRL_TX_CAL_EN_VAL(x)         (((uint32_t)(x) << SLC_RFCTRL_TX_CAL_EN_SHIFT) & SLC_RFCTRL_TX_CAL_EN_MASK)
#define SLC_RFCTRL_RX_CAL_EN_SHIFT          (3)
#define SLC_RFCTRL_RX_CAL_EN_MASK           (0x1U << SLC_RFCTRL_RX_CAL_EN_SHIFT)
#define SLC_RFCTRL_RX_CAL_EN_VAL(x)         (((uint32_t)(x) << SLC_RFCTRL_RX_CAL_EN_SHIFT) & SLC_RFCTRL_RX_CAL_EN_MASK)
#define SLC_RFCTRL_GPADC_EN_SHIFT           (4)
#define SLC_RFCTRL_GPADC_EN_MASK            (0x1U << SLC_RFCTRL_GPADC_EN_SHIFT)
#define SLC_RFCTRL_GPADC_EN_VAL(x)          (((uint32_t)(x) << SLC_RFCTRL_GPADC_EN_SHIFT) & SLC_RFCTRL_GPADC_EN_MASK)
#define SLC_RFCTRL_PLL_TX_MODE_MO_SHIFT     (8)
#define SLC_RFCTRL_PLL_TX_MODE_MO_MASK      (0x1U << SLC_RFCTRL_PLL_TX_MODE_MO_SHIFT)
#define SLC_RFCTRL_PLL_TX_MODE_MO_VAL(x)    (((uint32_t)(x) << SLC_RFCTRL_PLL_TX_MODE_MO_SHIFT) & SLC_RFCTRL_PLL_TX_MODE_MO_MASK)
#define SLC_RFCTRL_RX_LOW_GAIN_MODE_SHIFT   (9)
#define SLC_RFCTRL_RX_LOW_GAIN_MODE_MASK    (0x1U << SLC_RFCTRL_RX_LOW_GAIN_MODE_SHIFT)
#define SLC_RFCTRL_RX_LOW_GAIN_MODE_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_RX_LOW_GAIN_MODE_SHIFT) & SLC_RFCTRL_RX_LOW_GAIN_MODE_MASK)
#define SLC_RFCTRL_TX_EN_ME_SHIFT           (16)
#define SLC_RFCTRL_TX_EN_ME_MASK            (0x1U << SLC_RFCTRL_TX_EN_ME_SHIFT)
#define SLC_RFCTRL_TX_EN_ME_VAL(x)          (((uint32_t)(x) << SLC_RFCTRL_TX_EN_ME_SHIFT) & SLC_RFCTRL_TX_EN_ME_MASK)
#define SLC_RFCTRL_RX_EN_ME_SHIFT           (17)
#define SLC_RFCTRL_RX_EN_ME_MASK            (0x1U << SLC_RFCTRL_RX_EN_ME_SHIFT)
#define SLC_RFCTRL_RX_EN_ME_VAL(x)          (((uint32_t)(x) << SLC_RFCTRL_RX_EN_ME_SHIFT) & SLC_RFCTRL_RX_EN_ME_MASK)
#define SLC_RFCTRL_PLL_TX_MODE_SHIFT        (24)
#define SLC_RFCTRL_PLL_TX_MODE_MASK         (0x1U << SLC_RFCTRL_PLL_TX_MODE_SHIFT)
#define SLC_RFCTRL_PLL_TX_MODE_VAL(x)       (((uint32_t)(x) << SLC_RFCTRL_PLL_TX_MODE_SHIFT) & SLC_RFCTRL_PLL_TX_MODE_MASK)

#define SLC_RFCTRL_CAL_DCDC1M_START_SHIFT   (0)
#define SLC_RFCTRL_CAL_DCDC1M_START_MASK    (0x1U << SLC_RFCTRL_CAL_DCDC1M_START_SHIFT)
#define SLC_RFCTRL_CAL_DCDC1M_START_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_CAL_DCDC1M_START_SHIFT) & SLC_RFCTRL_CAL_DCDC1M_START_MASK)
#define SLC_RFCTRL_CAL_RC32K_START_SHIFT    (1)
#define SLC_RFCTRL_CAL_RC32K_START_MASK     (0x1U << SLC_RFCTRL_CAL_RC32K_START_SHIFT)
#define SLC_RFCTRL_CAL_RC32K_START_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_CAL_RC32K_START_SHIFT) & SLC_RFCTRL_CAL_RC32K_START_MASK)
#define SLC_RFCTRL_CAL_RC50M_START_SHIFT    (2)
#define SLC_RFCTRL_CAL_RC50M_START_MASK     (0x1U << SLC_RFCTRL_CAL_RC50M_START_SHIFT)
#define SLC_RFCTRL_CAL_RC50M_START_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_CAL_RC50M_START_SHIFT) & SLC_RFCTRL_CAL_RC50M_START_MASK)
#define SLC_RFCTRL_CAL_RXABB_START_SHIFT    (3)
#define SLC_RFCTRL_CAL_RXABB_START_MASK     (0x1U << SLC_RFCTRL_CAL_RXABB_START_SHIFT)
#define SLC_RFCTRL_CAL_RXABB_START_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_CAL_RXABB_START_SHIFT) & SLC_RFCTRL_CAL_RXABB_START_MASK)
#define SLC_RFCTRL_CAL_PMU_START_SHIFT      (4)
#define SLC_RFCTRL_CAL_PMU_START_MASK       (0x1U << SLC_RFCTRL_CAL_PMU_START_SHIFT)
#define SLC_RFCTRL_CAL_PMU_START_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_CAL_PMU_START_SHIFT) & SLC_RFCTRL_CAL_PMU_START_MASK)

#define RFCTRL_TXLPF_BIAS_TRIM_OP1_SHIFT    (0)
#define RFCTRL_TXLPF_BIAS_TRIM_OP1_MASK     (0x7U << RFCTRL_TXLPF_BIAS_TRIM_OP1_SHIFT)
#define RFCTRL_TXLPF_BIAS_TRIM_OP1_VAL(x)   (((uint32_t)(x) << RFCTRL_TXLPF_BIAS_TRIM_OP1_SHIFT) & RFCTRL_TXLPF_BIAS_TRIM_OP1_MASK)
#define RFCTRL_TXLPF_BIAS_TRIM_OP2_SHIFT    (4)
#define RFCTRL_TXLPF_BIAS_TRIM_OP2_MASK     (0x7U << RFCTRL_TXLPF_BIAS_TRIM_OP2_SHIFT)
#define RFCTRL_TXLPF_BIAS_TRIM_OP2_VAL(x)   (((uint32_t)(x) << RFCTRL_TXLPF_BIAS_TRIM_OP2_SHIFT) & RFCTRL_TXLPF_BIAS_TRIM_OP2_MASK)
#define RFCTRL_TXLPF_BIAS_TRIM_OP3_SHIFT    (8)
#define RFCTRL_TXLPF_BIAS_TRIM_OP3_MASK     (0x7U << RFCTRL_TXLPF_BIAS_TRIM_OP3_SHIFT)
#define RFCTRL_TXLPF_BIAS_TRIM_OP3_VAL(x)   (((uint32_t)(x) << RFCTRL_TXLPF_BIAS_TRIM_OP3_SHIFT) & RFCTRL_TXLPF_BIAS_TRIM_OP3_MASK)
#define RFCTRL_TXLPF_BIAS_TRIM_OP4_SHIFT    (12)
#define RFCTRL_TXLPF_BIAS_TRIM_OP4_MASK     (0x7U << RFCTRL_TXLPF_BIAS_TRIM_OP4_SHIFT)
#define RFCTRL_TXLPF_BIAS_TRIM_OP4_VAL(x)   (((uint32_t)(x) << RFCTRL_TXLPF_BIAS_TRIM_OP4_SHIFT) & RFCTRL_TXLPF_BIAS_TRIM_OP4_MASK)
#define RFCTRL_TXLPF_VCM_TRIM_SHIFT         (16)
#define RFCTRL_TXLPF_VCM_TRIM_MASK          (0x7U << RFCTRL_TXLPF_VCM_TRIM_SHIFT)
#define RFCTRL_TXLPF_VCM_TRIM_VAL(x)        (((uint32_t)(x) << RFCTRL_TXLPF_VCM_TRIM_SHIFT) & RFCTRL_TXLPF_VCM_TRIM_MASK)
#define SLC_RFCTRL_TXLPF_CTRIM_SHIFT        (20)
#define SLC_RFCTRL_TXLPF_CTRIM_MASK         (0x7FU << SLC_RFCTRL_TXLPF_CTRIM_SHIFT)
#define SLC_RFCTRL_TXLPF_CTRIM_VAL(x)       (((uint32_t)(x) << SLC_RFCTRL_TXLPF_CTRIM_SHIFT) & SLC_RFCTRL_TXLPF_CTRIM_MASK)

#define RFCTRL_RXABB_CBPF_MODESEL_MO_SHIFT  (0)
#define RFCTRL_RXABB_CBPF_MODESEL_MO_MASK   (0x3U << RFCTRL_RXABB_CBPF_MODESEL_MO_SHIFT)
#define RFCTRL_RXABB_CBPF_MODESEL_MO_VAL(x) (((uint32_t)(x) << RFCTRL_RXABB_CBPF_MODESEL_MO_SHIFT) & RFCTRL_RXABB_CBPF_MODESEL_MO_MASK)
#define RFCTRL_RXABB_CBPF_GPADC_EN_MO_SHIFT (2)
#define RFCTRL_RXABB_CBPF_GPADC_EN_MO_MASK  (0x1U << RFCTRL_RXABB_CBPF_GPADC_EN_MO_SHIFT)
#define RFCTRL_RXABB_CBPF_GPADC_EN_MO_VAL(x) (((uint32_t)(x) << RFCTRL_RXABB_CBPF_GPADC_EN_MO_SHIFT) & RFCTRL_RXABB_CBPF_GPADC_EN_MO_MASK)
#define RFCTRL_RXABB_CBPF_IQSWAP_SHIFT      (3)
#define RFCTRL_RXABB_CBPF_IQSWAP_MASK       (0x1U << RFCTRL_RXABB_CBPF_IQSWAP_SHIFT)
#define RFCTRL_RXABB_CBPF_IQSWAP_VAL(x)     (((uint32_t)(x) << RFCTRL_RXABB_CBPF_IQSWAP_SHIFT) & RFCTRL_RXABB_CBPF_IQSWAP_MASK)
#define RFCTRL_RXABB_CBPF_BWMODE_SHIFT      (4)
#define RFCTRL_RXABB_CBPF_BWMODE_MASK       (0x3U << RFCTRL_RXABB_CBPF_BWMODE_SHIFT)
#define RFCTRL_RXABB_CBPF_BWMODE_VAL(x)     (((uint32_t)(x) << RFCTRL_RXABB_CBPF_BWMODE_SHIFT) & RFCTRL_RXABB_CBPF_BWMODE_MASK)
#define RFCTRL_RXABB_CBPF_IFMODE_SHIFT      (8)
#define RFCTRL_RXABB_CBPF_IFMODE_MASK       (0x3U << RFCTRL_RXABB_CBPF_IFMODE_SHIFT)
#define RFCTRL_RXABB_CBPF_IFMODE_VAL(x)     (((uint32_t)(x) << RFCTRL_RXABB_CBPF_IFMODE_SHIFT) & RFCTRL_RXABB_CBPF_IFMODE_MASK)
#define RFCTRL_RXABB_CBPF_BIAS_CTRL_SHIFT   (12)
#define RFCTRL_RXABB_CBPF_BIAS_CTRL_MASK    (0x3U << RFCTRL_RXABB_CBPF_BIAS_CTRL_SHIFT)
#define RFCTRL_RXABB_CBPF_BIAS_CTRL_VAL(x)  (((uint32_t)(x) << RFCTRL_RXABB_CBPF_BIAS_CTRL_SHIFT) & RFCTRL_RXABB_CBPF_BIAS_CTRL_MASK)
#define RFCTRL_RXABB_CBPF_MODESEL_ME_SHIFT  (16)
#define RFCTRL_RXABB_CBPF_MODESEL_ME_MASK   (0x1U << RFCTRL_RXABB_CBPF_MODESEL_ME_SHIFT)
#define RFCTRL_RXABB_CBPF_MODESEL_ME_VAL(x) (((uint32_t)(x) << RFCTRL_RXABB_CBPF_MODESEL_ME_SHIFT) & RFCTRL_RXABB_CBPF_MODESEL_ME_MASK)
#define RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_SHIFT (17)
#define RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_MASK  (0x1U << RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_SHIFT)
#define RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_VAL(x) (((uint32_t)(x) << RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_SHIFT) & RFCTRL_RXABB_CBPF_OP_LOWPWR_EN_MASK)
#define RFCTRL_RXABB_CBPF_GPADC_EN_ME_SHIFT (18)
#define RFCTRL_RXABB_CBPF_GPADC_EN_ME_MASK  (0x1U << RFCTRL_RXABB_CBPF_GPADC_EN_ME_SHIFT)
#define RFCTRL_RXABB_CBPF_GPADC_EN_ME_VAL(x) (((uint32_t)(x) << RFCTRL_RXABB_CBPF_GPADC_EN_ME_SHIFT) & RFCTRL_RXABB_CBPF_GPADC_EN_ME_MASK)
#define RFCTRL_RXABB_CBPF_TEST_EN_SHIFT     (19)
#define RFCTRL_RXABB_CBPF_TEST_EN_MASK      (0x1U << RFCTRL_RXABB_CBPF_TEST_EN_SHIFT)
#define RFCTRL_RXABB_CBPF_TEST_EN_VAL(x)    (((uint32_t)(x) << RFCTRL_RXABB_CBPF_TEST_EN_SHIFT) & RFCTRL_RXABB_CBPF_TEST_EN_MASK)
#define RFCTRL_RXABB_CBPF_CTRIM_SHIFT       (20)
#define RFCTRL_RXABB_CBPF_CTRIM_MASK        (0x7FU << RFCTRL_RXABB_CBPF_CTRIM_SHIFT)
#define RFCTRL_RXABB_CBPF_CTRIM_VAL(x)      (((uint32_t)(x) << RFCTRL_RXABB_CBPF_CTRIM_SHIFT) & RFCTRL_RXABB_CBPF_CTRIM_MASK)
#define RFCTRL_RXABB_CBPF_I_TRIM_SHIFT      (28)
#define RFCTRL_RXABB_CBPF_I_TRIM_MASK       (0x3U << RFCTRL_RXABB_CBPF_I_TRIM_SHIFT)
#define RFCTRL_RXABB_CBPF_I_TRIM_VAL(x)     (((uint32_t)(x) << RFCTRL_RXABB_CBPF_I_TRIM_SHIFT) & RFCTRL_RXABB_CBPF_I_TRIM_MASK)

#define SLC_RFCTRL_RXTIA_MODE_CTRL_SHIFT    (0)
#define SLC_RFCTRL_RXTIA_MODE_CTRL_MASK     (0x1U << SLC_RFCTRL_RXTIA_MODE_CTRL_SHIFT)
#define SLC_RFCTRL_RXTIA_MODE_CTRL_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_RXTIA_MODE_CTRL_SHIFT) & SLC_RFCTRL_RXTIA_MODE_CTRL_MASK)
#define SLC_RFCTRL_RXTIA_COM_LPF_SEL_SHIFT  (1)
#define SLC_RFCTRL_RXTIA_COM_LPF_SEL_MASK   (0x1U << SLC_RFCTRL_RXTIA_COM_LPF_SEL_SHIFT)
#define SLC_RFCTRL_RXTIA_COM_LPF_SEL_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_RXTIA_COM_LPF_SEL_SHIFT) & SLC_RFCTRL_RXTIA_COM_LPF_SEL_MASK)
#define SLC_RFCTRL_RXTIA_SWAP_CTRL_SHIFT    (2)
#define SLC_RFCTRL_RXTIA_SWAP_CTRL_MASK     (0x1U << SLC_RFCTRL_RXTIA_SWAP_CTRL_SHIFT)
#define SLC_RFCTRL_RXTIA_SWAP_CTRL_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_RXTIA_SWAP_CTRL_SHIFT) & SLC_RFCTRL_RXTIA_SWAP_CTRL_MASK)
#define SLC_RFCTRL_RXTIA_CT_CTUNE_SHIFT     (4)
#define SLC_RFCTRL_RXTIA_CT_CTUNE_MASK      (0xFU << SLC_RFCTRL_RXTIA_CT_CTUNE_SHIFT)
#define SLC_RFCTRL_RXTIA_CT_CTUNE_VAL(x)    (((uint32_t)(x) << SLC_RFCTRL_RXTIA_CT_CTUNE_SHIFT) & SLC_RFCTRL_RXTIA_CT_CTUNE_MASK)
#define SLC_RFCTRL_RXTIA_START_CTRL_SHIFT   (8)
#define SLC_RFCTRL_RXTIA_START_CTRL_MASK    (0x3U << SLC_RFCTRL_RXTIA_START_CTRL_SHIFT)
#define SLC_RFCTRL_RXTIA_START_CTRL_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_RXTIA_START_CTRL_SHIFT) & SLC_RFCTRL_RXTIA_START_CTRL_MASK)
#define SLC_RFCTRL_RXTIA_I_TRIM_SHIFT       (12)
#define SLC_RFCTRL_RXTIA_I_TRIM_MASK        (0x3U << SLC_RFCTRL_RXTIA_I_TRIM_SHIFT)
#define SLC_RFCTRL_RXTIA_I_TRIM_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXTIA_I_TRIM_SHIFT) & SLC_RFCTRL_RXTIA_I_TRIM_MASK)
#define SLC_RFCTRL_RXMIXER_VBCT_SHIFT       (16)
#define SLC_RFCTRL_RXMIXER_VBCT_MASK        (0x7U << SLC_RFCTRL_RXMIXER_VBCT_SHIFT)
#define SLC_RFCTRL_RXMIXER_VBCT_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXMIXER_VBCT_SHIFT) & SLC_RFCTRL_RXMIXER_VBCT_MASK)

#define SLC_RFCTRL_TX_RESERVE_LV_SHIFT      (0)
#define SLC_RFCTRL_TX_RESERVE_LV_MASK       (0xFFU << SLC_RFCTRL_TX_RESERVE_LV_SHIFT)
#define SLC_RFCTRL_TX_RESERVE_LV_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_TX_RESERVE_LV_SHIFT) & SLC_RFCTRL_TX_RESERVE_LV_MASK)
#define SLC_RFCTRL_TX_RESERVE_HV_SHIFT      (8)
#define SLC_RFCTRL_TX_RESERVE_HV_MASK       (0xFFU << SLC_RFCTRL_TX_RESERVE_HV_SHIFT)
#define SLC_RFCTRL_TX_RESERVE_HV_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_TX_RESERVE_HV_SHIFT) & SLC_RFCTRL_TX_RESERVE_HV_MASK)

#define SLC_RFCTRL_RXADC_RST_MO_SHIFT       (0)
#define SLC_RFCTRL_RXADC_RST_MO_MASK        (0x1U << SLC_RFCTRL_RXADC_RST_MO_SHIFT)
#define SLC_RFCTRL_RXADC_RST_MO_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXADC_RST_MO_SHIFT) & SLC_RFCTRL_RXADC_RST_MO_MASK)
#define SLC_RFCTRL_RXADC_CNT_EN_SHIFT       (1)
#define SLC_RFCTRL_RXADC_CNT_EN_MASK        (0x1U << SLC_RFCTRL_RXADC_CNT_EN_SHIFT)
#define SLC_RFCTRL_RXADC_CNT_EN_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXADC_CNT_EN_SHIFT) & SLC_RFCTRL_RXADC_CNT_EN_MASK)
#define SLC_RFCTRL_RXADC_DEM_EN_SHIFT       (2)
#define SLC_RFCTRL_RXADC_DEM_EN_MASK        (0x1U << SLC_RFCTRL_RXADC_DEM_EN_SHIFT)
#define SLC_RFCTRL_RXADC_DEM_EN_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXADC_DEM_EN_SHIFT) & SLC_RFCTRL_RXADC_DEM_EN_MASK)
#define SLC_RFCTRL_RXADC_NSPATH_EN_SHIFT    (3)
#define SLC_RFCTRL_RXADC_NSPATH_EN_MASK     (0x1U << SLC_RFCTRL_RXADC_NSPATH_EN_SHIFT)
#define SLC_RFCTRL_RXADC_NSPATH_EN_VAL(x)   (((uint32_t)(x) << SLC_RFCTRL_RXADC_NSPATH_EN_SHIFT) & SLC_RFCTRL_RXADC_NSPATH_EN_MASK)
#define SLC_RFCTRL_RXADC_RST_ME_SHIFT       (16)
#define SLC_RFCTRL_RXADC_RST_ME_MASK        (0x1U << SLC_RFCTRL_RXADC_RST_ME_SHIFT)
#define SLC_RFCTRL_RXADC_RST_ME_VAL(x)      (((uint32_t)(x) << SLC_RFCTRL_RXADC_RST_ME_SHIFT) & SLC_RFCTRL_RXADC_RST_ME_MASK)

#define SLC_RFCTRL_GPADC_BUF_SEL_SHIFT      (4)
#define SLC_RFCTRL_GPADC_BUF_SEL_MASK       (0x3U << SLC_RFCTRL_GPADC_BUF_SEL_SHIFT)
#define SLC_RFCTRL_GPADC_BUF_SEL_VAL(x)     (((uint32_t)(x) << SLC_RFCTRL_GPADC_BUF_SEL_SHIFT) & SLC_RFCTRL_GPADC_BUF_SEL_MASK)

#define SLC_RFCTRL_POWER_CNTL_LDO_SHIFT     (0)
#define SLC_RFCTRL_POWER_CNTL_LDO_MASK      (0xFFFU << SLC_RFCTRL_POWER_CNTL_LDO_SHIFT)
#define SLC_RFCTRL_POWER_CNTL_LDO_VAL(x)    (((uint32_t)(x) << SLC_RFCTRL_POWER_CNTL_LDO_SHIFT) & SLC_RFCTRL_POWER_CNTL_LDO_MASK)
#define SLC_RFCTRL_POWER_CNTL_PPA_H_SHIFT   (20)
#define SLC_RFCTRL_POWER_CNTL_PPA_H_MASK    (0x1FU << SLC_RFCTRL_POWER_CNTL_PPA_H_SHIFT)
#define SLC_RFCTRL_POWER_CNTL_PPA_H_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_POWER_CNTL_PPA_H_SHIFT) & SLC_RFCTRL_POWER_CNTL_PPA_H_MASK)
#define SLC_RFCTRL_POWER_CNTL_PPA_L_SHIFT   (4)
#define SLC_RFCTRL_POWER_CNTL_PPA_L_MASK    (0xFFU << SLC_RFCTRL_POWER_CNTL_PPA_L_SHIFT)
#define SLC_RFCTRL_POWER_CNTL_PPA_L_VAL(x)  (((uint32_t)(x) << SLC_RFCTRL_POWER_CNTL_PPA_L_SHIFT) & SLC_RFCTRL_POWER_CNTL_PPA_L_MASK)
#define SLC_RFCTRL_POWER_CNTL_RESERVE_SHIFT (0)
#define SLC_RFCTRL_POWER_CNTL_RESERVE_MASK  (0x7U << SLC_RFCTRL_POWER_CNTL_RESERVE_SHIFT)
#define SLC_RFCTRL_POWER_CNTL_RESERVE_VAL(x) (((uint32_t)(x) << SLC_RFCTRL_POWER_CNTL_RESERVE_SHIFT) & SLC_RFCTRL_POWER_CNTL_RESERVE_MASK)

typedef struct
{
    __IOM uint32_t SYNC_CTRL;           // 0x00
    __IOM uint32_t GAIN_CTRL;           // 0x04
    __IOM uint32_t AGC_CTRL;            // 0x08
    __IOM uint32_t AGC_FILT_OP;         // 0x0C
    __IOM uint32_t AGC_TIME_CTRL;       // 0x10
    __IOM uint32_t AGC_SETTLE_T1_LUT0;  // 0x14
    __IOM uint32_t AGC_SETTLE_T1_LUT1;  // 0x18
    __IOM uint32_t AGC_SETTLE_T1_LUT2;  // 0x1C
    __IOM uint32_t AGC_SETTLE_T1_LUT3;  // 0x20
    __IOM uint32_t AGC_SETTLE_T1_LUT4;  // 0x24
    __IOM uint32_t AGC_SETTLE_T1_LUT5;  // 0x28
    __IOM uint32_t AGC_SETTLE_T1_LUT6;  // 0x2C
    __IOM uint32_t BHF_AGC_LUT1;        // 0x30
    __IOM uint32_t BHF_AGC_LUT2;        // 0x34
    __IOM uint32_t BHF_AGC_LUT3;        // 0x38
    __IOM uint32_t BHF_AGC_LUT4;        // 0x3C
    __IOM uint32_t BHF_AGC_LUT5;        // 0x40
    __IOM uint32_t BHF_AGC_LUT6;        // 0x44
    __IOM uint32_t BHF_AGC_LUT7;        // 0x48
    __IOM uint32_t BHF_AGC_LUT8;        // 0x4C
    __IOM uint32_t BHF_AGC_LUT9;        // 0x50
    __IOM uint32_t AGC_LMT_LUT0;        // 0x54
    __IOM uint32_t AGC_LMT_LUT1;        // 0x58
    __IOM uint32_t AGC_LMT_LUT2;        // 0x5C
    __IOM uint32_t AGC_LMT_LUT3;        // 0x60
    __IOM uint32_t AGC_LMT_LUT4;        // 0x64
    __IOM uint32_t AGC_LMT_LUT5;        // 0x68
    __IOM uint32_t AGC_LMT_LUT6;        // 0x6C
    __IOM uint32_t AGC_LMT_LUT7;        // 0x70
    __IOM uint32_t AGC_LMT_LUT8;        // 0x74
    __IOM uint32_t AGC_LMT_LUT9;        // 0x78
    __IOM uint32_t AGC_LMT_LUT10;       // 0x7C
    __IOM uint32_t AGC_BHF_LUT0;        // 0x80
    __IOM uint32_t AGC_BHF_LUT1;        // 0x84
    __IOM uint32_t AGC_BHF_LUT2;        // 0x88
    __IOM uint32_t AGC_BHF_LUT3;        // 0x8C
    __IOM uint32_t AGC_BHF_LUT4;        // 0x90
    __IOM uint32_t AGC_BHF_LUT5;        // 0x94
    __IOM uint32_t AGC_BHF_LUT6;        // 0x98
    __IOM uint32_t AGC_BHF_LUT7;        // 0x9C
    __IOM uint32_t AGC_BHF_LUT8;        // 0xA0
    __IOM uint32_t AGC_BHF_LUT9;        // 0xA4
    __IOM uint32_t AGC_BHF_LUT10;       // 0xA8
    __IOM uint32_t AGC_BHF_LUT11;       // 0xAC
    __IOM uint32_t AGC_BHF_LUT12;       // 0xB0
    __IOM uint32_t AGC_LMT_CTRL;        // 0xB4
    __IOM uint32_t AGC_BHF_CTRL;        // 0xB8
} rf_agc_handle_t;

#define AGC_AGC_OPT_SHIFT                   (6)
#define AGC_AGC_OPT_MASK                    (0x3U << AGC_AGC_OPT_SHIFT)
#define AGC_AGC_OPT_VAL(x)                  (((uint32_t)(x) << AGC_AGC_OPT_SHIFT) & AGC_AGC_OPT_MASK)
#define AGC_BHF_AGC_PFS_STEP_SHIFT          (24)
#define AGC_BHF_AGC_PFS_STEP_MASK           (0x7U << AGC_BHF_AGC_PFS_STEP_SHIFT)
#define AGC_BHF_AGC_PFS_STEP_VAL(x)         (((uint32_t)(x) << AGC_BHF_AGC_PFS_STEP_SHIFT) & AGC_BHF_AGC_PFS_STEP_MASK)

#define AGC_GET_PRXADC_TIME_SHIFT           (24)
#define AGC_GET_PRXADC_TIME_MASK            (0x7U << AGC_GET_PRXADC_TIME_SHIFT)
#define AGC_GET_PRXADC_TIME_VAL(x)          (((uint32_t)(x) << AGC_GET_PRXADC_TIME_SHIFT) & AGC_GET_PRXADC_TIME_MASK)

#define AGC_RXABB_CBPF_GAIN1_LUT0_SHIFT     (0)
#define AGC_RXABB_CBPF_GAIN1_LUT0_MASK      (0x7U << AGC_RXABB_CBPF_GAIN1_LUT0_SHIFT)
#define AGC_RXABB_CBPF_GAIN1_LUT0_VAL(x)    (((uint32_t)(x) << AGC_RXABB_CBPF_GAIN1_LUT0_SHIFT) & AGC_RXABB_CBPF_GAIN1_LUT0_MASK)
#define AGC_RXABB_CBPF_GAIN2_LUT0_SHIFT     (4)
#define AGC_RXABB_CBPF_GAIN2_LUT0_MASK      (0x7U << AGC_RXABB_CBPF_GAIN2_LUT0_SHIFT)
#define AGC_RXABB_CBPF_GAIN2_LUT0_VAL(x)    (((uint32_t)(x) << AGC_RXABB_CBPF_GAIN2_LUT0_SHIFT) & AGC_RXABB_CBPF_GAIN2_LUT0_MASK)

typedef struct
{
    __IOM uint32_t REG_RESERVED;        // 0x00
    __IOM uint32_t PLLDIG_CTRL;         // 0x04
    __IOM uint32_t PD_CTRL0;            // 0x08
    __IOM uint32_t PD_CTRL1;            // 0x0C
    __IOM uint32_t PD_CTRL2;            // 0x10
    __IOM uint32_t PD_CTRL3;            // 0x14
    __IOM uint32_t PD_CTRL4;            // 0x18
    __IOM uint32_t PD_CTRL6;            // 0x1C
    __IOM uint32_t PD_CTRL7;            // 0x20
    __IOM uint32_t PD_CTRL8;            // 0x24
    __IOM uint32_t PD_CTRL9;            // 0x28
    __IOM uint32_t PFD_CTRL;            // 0x2C
    __IOM uint32_t CP_CTRL0;            // 0x30
    __IOM uint32_t CP_CTRL1;            // 0x34
    __IOM uint32_t CP_CTRL2;            // 0x38
    __IOM uint32_t LPF_CTRL;            // 0x3C
    __IOM uint32_t VCO_AMP_CTRL0;       // 0x40
    __IOM uint32_t VCO_AMP_CTRL1;       // 0x44
    __IOM uint32_t VCO_CTRL;            // 0x48
    __IOM uint32_t VCO_AFC_CTRL0;       // 0x4C
    __IOM uint32_t VCO_AFC_CTRL1;       // 0x50
    __IOM uint32_t VCO_AFC_CTRL2;       // 0x54
    __IOM uint32_t VCO_AFC_CTRL3;       // 0x58
    __IOM uint32_t VCO_AFC_CTRL4;       // 0x5C
    __IOM uint32_t VCO_AFC_CTRL5;       // 0x60
    __IOM uint32_t PK_CTRL;             // 0x64
    __IOM uint32_t MMD_CTRL0;           // 0x68
    __IOM uint32_t MMD_CTRL1;           // 0x6C
    __IOM uint32_t AFC_CTRL;            // 0x70
    __IOM uint32_t CYCLE_SLIP_CTRL;     // 0x74
    __IOM uint32_t DTEMP_CTRL0;         // 0x78
    __IOM uint32_t DTEMP_CTRL1;         // 0x7C
    __IOM uint32_t DTEMP_CTRL2;         // 0x80
    __IOM uint32_t DTEMP_CTRL3;         // 0x84
    __IOM uint32_t DTEMP_CTRL4;         // 0x88
    __IOM uint32_t DTEMP_CTRL5;         // 0x8C
    __IOM uint32_t DTEMP_CTRL6;         // 0x90
    __IOM uint32_t DTEMP_CTRL7;         // 0x94
    __IOM uint32_t DTEMP_RPT;           // 0x98
    __IOM uint32_t LDO_CTRL;            // 0x9C
    __IOM uint32_t SDM_CTRL0;           // 0xA0
    __IOM uint32_t SDM_FREQ_CFG;        // 0xA4
    __IOM uint32_t FSM_CTRL;            // 0xA8
    __IOM uint32_t ST_CTRL0;            // 0xAC
    __IOM uint32_t ST_CTRL1;            // 0xB0
    __IOM uint32_t ST_CTRL2;            // 0xB4
    __IOM uint32_t LO_CTRL;             // 0xB8
    __IOM uint32_t TX_FREQ_INT;         // 0xBC
    __IOM uint32_t TX_FREQ_FRAC;        // 0xC0
    __IOM uint32_t INTER_FREQ;          // 0xC4
    __IOM uint32_t POLAR_CTRL;          // 0xC8
    __IOM uint32_t LOOP_LDO_CTRL;       // 0xCC
    __IOM uint32_t PD_VCOKDAC_CTRL;     // 0xD0
    __IOM uint32_t PD_DAC_CTRL;         // 0xD4
    __IOM uint32_t DAC_RSTN_CTRL;       // 0xD8
    __IOM uint32_t DAC_START_CTRL;      // 0xDC
    __IOM uint32_t CAL_DAC_CTRL;        // 0xE0
    __IOM uint32_t CAL_DAC_INIT;        // 0xE4
    __IOM uint32_t CAL_DAC_CNT;         // 0xE8
    __IOM uint32_t CAL_DAC_TGT;         // 0xEC
    __IOM uint32_t CAL_DAC_RPT;         // 0xF0
    __IOM uint32_t DAC_CTRL;            // 0xF4
    __IOM uint32_t RFPLL_RESERVE;       // 0xF8
} rf_pll_handle_t;

#define PLL_SW_PLL_EN_SHIFT             (0)
#define PLL_SW_PLL_EN_MASK              (0x1 << PLL_SW_PLL_EN_SHIFT)
#define PLL_SW_PLL_EN_VAL(x)            (((uint32_t)(x) << PLL_SW_PLL_EN_SHIFT) & PLL_SW_PLL_EN_MASK)
#define PLL_DBG_PLL_EN_SHIFT            (1)
#define PLL_DBG_PLL_EN_MASK             (0x1 << PLL_DBG_PLL_EN_SHIFT)
#define PLL_DBG_PLL_EN_VAL(x)           (((uint32_t)(x) << PLL_DBG_PLL_EN_SHIFT) & PLL_DBG_PLL_EN_MASK)
#define PLL_AFC_START_TX_SHIFT          (2)
#define PLL_AFC_START_TX_MASK           (0x1 << PLL_AFC_START_TX_SHIFT)
#define PLL_AFC_START_TX_VAL(x)         (((uint32_t)(x) << PLL_AFC_START_TX_SHIFT) & PLL_AFC_START_TX_MASK)
#define PLL_AFC_START_RX_SHIFT          (3)
#define PLL_AFC_START_RX_MASK           (0x1 << PLL_AFC_START_RX_SHIFT)
#define PLL_AFC_START_RX_VAL(x)         (((uint32_t)(x) << PLL_AFC_START_RX_SHIFT) & PLL_AFC_START_RX_MASK)
#define PLL_RPT_AFC_DONE_SHIFT          (4)
#define PLL_RPT_AFC_DONE_MASK           (0x1 << PLL_RPT_AFC_DONE_SHIFT)
#define PLL_RPT_AFC_DONE_VAL(x)         (((uint32_t)(x) << PLL_RPT_AFC_DONE_SHIFT) & PLL_RPT_AFC_DONE_MASK)
#define PLL_CAL_DAC_START_SHIFT         (5)
#define PLL_CAL_DAC_START_MASK          (0x1 << PLL_CAL_DAC_START_SHIFT)
#define PLL_CAL_DAC_START_VAL(x)        (((uint32_t)(x) << PLL_CAL_DAC_START_SHIFT) & PLL_CAL_DAC_START_MASK)

#define PLL_TUNE_SEL_REG_SHIFT          (20)
#define PLL_TUNE_SEL_REG_MASK           (0x1 << PLL_TUNE_SEL_REG_SHIFT)
#define PLL_TUNE_SEL_REG_VAL(x)         (((uint32_t)(x) << PLL_TUNE_SEL_REG_SHIFT) & PLL_TUNE_SEL_REG_MASK)

#define PLL_AFC_FTUNE_SHIFT             (0)
#define PLL_AFC_FTUNE_MASK              (0xFU << PLL_AFC_FTUNE_SHIFT)
#define PLL_AFC_FTUNE_VAL(x)            (((uint32_t)(x) << PLL_AFC_FTUNE_SHIFT) & PLL_AFC_FTUNE_MASK)
#define PLL_AFC_CTUNE_SHIFT             (4)
#define PLL_AFC_CTUNE_MASK              (0x3FU << PLL_AFC_CTUNE_SHIFT)
#define PLL_AFC_CTUNE_VAL(x)            (((uint32_t)(x) << PLL_AFC_CTUNE_SHIFT) & PLL_AFC_CTUNE_MASK)
#define PLL_AFC_FTUNE_MANUAL_SHIFT      (10)
#define PLL_AFC_FTUNE_MANUAL_MASK       (0xFU << PLL_AFC_FTUNE_MANUAL_SHIFT)
#define PLL_AFC_FTUNE_MANUAL_VAL(x)     (((uint32_t)(x) << PLL_AFC_FTUNE_MANUAL_SHIFT) & PLL_AFC_FTUNE_MANUAL_MASK)
#define PLL_AFC_CTUNE_MANUAL_SHIFT      (14)
#define PLL_AFC_CTUNE_MANUAL_MASK       (0x3FU << PLL_AFC_CTUNE_MANUAL_SHIFT)
#define PLL_AFC_CTUNE_MANUAL_VAL(x)     (((uint32_t)(x) << PLL_AFC_CTUNE_MANUAL_SHIFT) & PLL_AFC_CTUNE_MANUAL_MASK)
#define PLL_AFC_FTUNE_SEL_SHIFT         (20)
#define PLL_AFC_FTUNE_SEL_MASK          (0x1U << PLL_AFC_FTUNE_SEL_SHIFT)
#define PLL_AFC_FTUNE_SEL_VAL(x)        (((uint32_t)(x) << PLL_AFC_FTUNE_SEL_SHIFT) & PLL_AFC_FTUNE_SEL_MASK)
#define PLL_AFC_CTUNE_SEL_SHIFT         (21)
#define PLL_AFC_CTUNE_SEL_MASK          (0x1U << PLL_AFC_CTUNE_SEL_SHIFT)
#define PLL_AFC_CTUNE_SEL_VAL(x)        (((uint32_t)(x) << PLL_AFC_CTUNE_SEL_SHIFT) & PLL_AFC_CTUNE_SEL_MASK)

#define PLL_LO_MODE_SEL_SHIFT           (0)
#define PLL_LO_MODE_SEL_MASK            (0x3U << PLL_LO_MODE_SEL_SHIFT)
#define PLL_LO_MODE_SEL_VAL(x)          (((uint32_t)(x) << PLL_LO_MODE_SEL_SHIFT) & PLL_LO_MODE_SEL_MASK)
#define PLL_LO_DIV_BAND_SHIFT           (2)
#define PLL_LO_DIV_BAND_MASK            (0x3U << PLL_LO_DIV_BAND_SHIFT)
#define PLL_LO_DIV_BAND_VAL(x)          (((uint32_t)(x) << PLL_LO_DIV_BAND_SHIFT) & PLL_LO_DIV_BAND_MASK)
#define PLL_LO_BAND_MULT_SHIFT          (4)
#define PLL_LO_BAND_MULT_MASK           (0x3U << PLL_LO_BAND_MULT_SHIFT)
#define PLL_LO_BAND_MULT_VAL(x)         (((uint32_t)(x) << PLL_LO_BAND_MULT_SHIFT) & PLL_LO_BAND_MULT_MASK)
#define PLL_LO_EN_POLAR_MO_SHIFT        (6)
#define PLL_LO_EN_POLAR_MO_MASK         (0x1U << PLL_LO_EN_POLAR_MO_SHIFT)
#define PLL_LO_EN_POLAR_MO_VAL(x)       (((uint32_t)(x) << PLL_LO_EN_POLAR_MO_SHIFT) & PLL_LO_EN_POLAR_MO_MASK)
#define PLL_LO_DIV_MODE_SEL_SHIFT       (16)
#define PLL_LO_DIV_MODE_SEL_MASK        (0x1U << PLL_LO_DIV_MODE_SEL_SHIFT)
#define PLL_LO_DIV_MODE_SEL_VAL(x)      (((uint32_t)(x) << PLL_LO_DIV_MODE_SEL_SHIFT) & PLL_LO_DIV_MODE_SEL_MASK)
#define PLL_LO_BAND_SEL_SHIFT           (18)
#define PLL_LO_BAND_SEL_MASK            (0x3U << PLL_LO_BAND_SEL_SHIFT)
#define PLL_LO_BAND_SEL_VAL(x)          (((uint32_t)(x) << PLL_LO_BAND_SEL_SHIFT) & PLL_LO_BAND_SEL_MASK)
#define PLL_LO_EN_POLAR_ME_SHIFT        (22)
#define PLL_LO_EN_POLAR_ME_MASK         (0x1U << PLL_LO_EN_POLAR_ME_SHIFT)
#define PLL_LO_EN_POLAR_ME_VAL(x)       (((uint32_t)(x) << PLL_LO_EN_POLAR_ME_SHIFT) & PLL_LO_EN_POLAR_ME_MASK)

#define PLL_KDAC_GAIN_SHIFT             (24)
#define PLL_KDAC_GAIN_MASK              (0xFFU << PLL_KDAC_GAIN_SHIFT)
#define PLL_KDAC_GAIN_VAL(x)            (((uint32_t)(x) << PLL_KDAC_GAIN_SHIFT) & PLL_KDAC_GAIN_MASK)

#define RFPLL_PEAKDET_CON_VREF_1P1_SHIFT    (0)
#define RFPLL_PEAKDET_CON_VREF_1P1_MASK     (0x7U << RFPLL_PEAKDET_CON_VREF_1P1_SHIFT)
#define RFPLL_PEAKDET_CON_VREF_1P1_VAL(x)   (((uint32_t)(x) << RFPLL_PEAKDET_CON_VREF_1P1_SHIFT) & RFPLL_PEAKDET_CON_VREF_1P1_MASK)

#define PLL_TX_FREQ_INT_SHIFT           (0)
#define PLL_TX_FREQ_INT_MASK            (0x7FF << PLL_TX_FREQ_INT_SHIFT)
#define PLL_TX_FREQ_INT_VAL(x)          (((uint32_t)(x) << PLL_TX_FREQ_INT_SHIFT) & PLL_TX_FREQ_INT_MASK)
#define PLL_TX_FREQ_FRAC_SHIFT          (0)
#define PLL_TX_FREQ_FRAC_MASK           (0xFFFFFF << PLL_TX_FREQ_FRAC_SHIFT)
#define PLL_TX_FREQ_FRAC_VAL(x)         (((uint32_t)(x) << PLL_TX_FREQ_FRAC_SHIFT) & PLL_TX_FREQ_FRAC_MASK)

#define PLL_INTER_FREQ_SHIFT            (0)
#define PLL_INTER_FREQ_MASK             (0x7FFFFFF << PLL_INTER_FREQ_SHIFT)
#define PLL_INTER_FREQ_VAL(x)           (((uint32_t)(x) << PLL_INTER_FREQ_SHIFT) & PLL_INTER_FREQ_MASK)

#define RFPLL_DAC_TIA_CTRIM_SHIFT       (20)
#define RFPLL_DAC_TIA_CTRIM_MASK        (0x7FU << RFPLL_DAC_TIA_CTRIM_SHIFT)
#define RFPLL_DAC_TIA_CTRIM_VAL(x)      (((uint32_t)(x) << RFPLL_DAC_TIA_CTRIM_SHIFT) & RFPLL_DAC_TIA_CTRIM_MASK)

#define RFPLL_RESERVE_IN_SHIFT          (0)
#define RFPLL_RESERVE_IN_MASK           (0xFFU << RFPLL_RESERVE_IN_SHIFT)
#define RFPLL_RESERVE_IN_VAL(x)         (((uint32_t)(x) << RFPLL_RESERVE_IN_SHIFT) & RFPLL_RESERVE_IN_MASK)

#define RFPLL_FSM_HOLD_SHIFT            (0)
#define RFPLL_FSM_HOLD_MASK             (0xFFU << RFPLL_FSM_HOLD_SHIFT)
#define RFPLL_FSM_HOLD_VAL(x)           (((uint32_t)(x) << RFPLL_FSM_HOLD_SHIFT) & RFPLL_FSM_HOLD_MASK)
#define RFPLL_FSM_SKIPPER_SHIFT         (8)
#define RFPLL_FSM_SKIPPER_MASK          (0x7FU << RFPLL_FSM_SKIPPER_SHIFT)
#define RFPLL_FSM_SKIPPER_VAL(x)        (((uint32_t)(x) << RFPLL_FSM_SKIPPER_SHIFT) & RFPLL_FSM_SKIPPER_MASK)
#define RFPLL_ANA_SIGNAL_SEQ_SHIFT      (15)
#define RFPLL_ANA_SIGNAL_SEQ_MASK       (0x1U << RFPLL_ANA_SIGNAL_SEQ_SHIFT)
#define RFPLL_ANA_SIGNAL_SEQ_VAL(x)     (((uint32_t)(x) << RFPLL_ANA_SIGNAL_SEQ_SHIFT) & RFPLL_ANA_SIGNAL_SEQ_MASK)

#define RFPLL_AMP_CTR0_CTUNE_SHIFT      (4)
#define RFPLL_AMP_CTR0_CTUNE_MASK       (0x3FU << RFPLL_AMP_CTR0_CTUNE_SHIFT)
#define RFPLL_AMP_CTR0_CTUNE_VAL(x)     (((uint32_t)(x) << RFPLL_AMP_CTR0_CTUNE_SHIFT) & RFPLL_AMP_CTR0_CTUNE_MASK)
#define RFPLL_AMP_CTR0_FTUNE_SHIFT      (0)
#define RFPLL_AMP_CTR0_FTUNE_MASK       (0xFU << RFPLL_AMP_CTR0_FTUNE_SHIFT)
#define RFPLL_AMP_CTR0_FTUNE_VAL(x)     (((uint32_t)(x) << RFPLL_AMP_CTR0_FTUNE_SHIFT) & RFPLL_AMP_CTR0_FTUNE_MASK)

typedef struct
{
    __IOM uint32_t DFE_WORK_MODE;        // 0x00
    __IOM uint32_t DFE_SOFT_RESET;       // 0x04
    __IOM uint32_t DFE_CFG_BANDWIDTH;    // 0x08
    __IOM uint32_t DFE_FIR59_BYPASS;     // 0x0C
    __IOM uint32_t DFE_FIR59_TX_COMB0;   // 0x10
    __IOM uint32_t DFE_FIR59_TX_COMB1;   // 0x14
    __IOM uint32_t DFE_FIR59_TX_COMB2;   // 0x18
    __IOM uint32_t DFE_FIR59_TX_COMB3;   // 0x1C
    __IOM uint32_t DFE_FIR59_TX_COMB4;   // 0x20
    __IOM uint32_t DFE_FIR59_TX_COMB5;   // 0x24
    __IOM uint32_t DFE_FIR59_TX_COMB6;   // 0x28
    __IOM uint32_t DFE_FIR59_TX_COMB7;   // 0x2C
    __IOM uint32_t DFE_FIR59_TX_COMB8;   // 0x30
    __IOM uint32_t DFE_FIR59_TX_COMB9;   // 0x34
    __IOM uint32_t DFE_FIR59_TX_COMB10;  // 0x38
    __IOM uint32_t DFE_FIR59_TX_COMB11;  // 0x3C
    __IOM uint32_t DFE_FIR59_TX_COMB12;  // 0x40
    __IOM uint32_t DFE_FIR59_TX_COMB13;  // 0x44
    __IOM uint32_t DFE_FIR59_TX_COMB14;  // 0x48
    __IOM uint32_t DFE_FIR59_RX_COMB0;   // 0x4C
    __IOM uint32_t DFE_FIR59_RX_COMB1;   // 0x50
    __IOM uint32_t DFE_FIR59_RX_COMB2;   // 0x54
    __IOM uint32_t DFE_FIR59_RX_COMB3;   // 0x58
    __IOM uint32_t DFE_FIR59_RX_COMB4;   // 0x5C
    __IOM uint32_t DFE_FIR59_RX_COMB5;   // 0x60
    __IOM uint32_t DFE_FIR59_RX_COMB6;   // 0x64
    __IOM uint32_t DFE_FIR59_RX_COMB7;   // 0x68
    __IOM uint32_t DFE_FIR59_RX_COMB8;   // 0x6C
    __IOM uint32_t DFE_FIR59_RX_COMB9;   // 0x70
    __IOM uint32_t DFE_FIR59_RX_COMB10;  // 0x74
    __IOM uint32_t DFE_FIR59_RX_COMB11;  // 0x78
    __IOM uint32_t DFE_FIR59_RX_COMB12;  // 0x7C
    __IOM uint32_t DFE_FIR59_RX_COMB13;  // 0x80
    __IOM uint32_t DFE_FIR59_RX_COMB14;  // 0x84
    __IOM uint32_t DFE_FIR19_TX_COMB0;   // 0x88
    __IOM uint32_t DFE_FIR19_TX_COMB1;   // 0x8C
    __IOM uint32_t DFE_FIR19_TX_COMB2;   // 0x90
    __IOM uint32_t DFE_FIR19_TX_COMB3;   // 0x94
    __IOM uint32_t DFE_FIR19_TX_COMB4;   // 0x98
    __IOM uint32_t DFE_FIR19_RX_COMB0;   // 0x9C
    __IOM uint32_t DFE_FIR19_RX_COMB1;   // 0xA0
    __IOM uint32_t DFE_FIR19_RX_COMB2;   // 0xA4
    __IOM uint32_t DFE_FIR19_RX_COMB3;   // 0xA8
    __IOM uint32_t DFE_FIR19_RX_COMB4;   // 0xAC
    __IOM uint32_t DFE_FIR19_DEL_KEEP_PNT;   // 0xB0
    __IOM uint32_t DFE_FIR19_DEL_KEEP_PNT_BYPASS;   // 0xB4
    __IOM uint32_t DFE_DIG_DOWN_CONV;   // 0xB8
    __IOM uint32_t DFE_CALIB_WAIT_TIME; // 0xBC
    __IOM uint32_t DFE_CALIB_START;     // 0xC0
    __IOM uint32_t DFE_CALIB_PARAMETER; // 0xC4
    __IOM uint32_t DFE_CALIB_SIN_FCW;   // 0xC8
    __IOM uint32_t DFE_CALIB_DC_VT;     // 0xCC
    __IOM uint32_t DFE_CALIB_FFT_FCW;   // 0xD0
    __IOM uint32_t DFE_CALIB_FINISH;    // 0xD4
    __IOM uint32_t DFE_CALIB_DC_RSLT;   // 0xD8
    __IOM uint32_t DFE_CALIB_FFT_RSLTI; // 0xDC
    __IOM uint32_t DFE_CALIB_FFT_RSLTQ; // 0xE0
    __IOM uint32_t DFE_DC0_PARA_CFG;    // 0xE4
    __IOM uint32_t DFE_DC0_COMP_VAL;    // 0xE8
    __IOM uint32_t DFE_MNT_DC0_EST_VAL; // 0xEC
    __IOM uint32_t DFE_DC1_PARA_CFG;    // 0xF0
    __IOM uint32_t DFE_DC1_COMP_VAL;    // 0xF4
    __IOM uint32_t DFE_MNT_DC1_EST_VAL; // 0xF8
    __IOM uint32_t DFE_CFG_AMP_COMP;    // 0xFC
    __IOM uint32_t DFE_CFG_PHASE_COMP;  // 0x100
    __IOM uint32_t DFE_CFG_DC_COMP;     // 0x104
    __IOM uint32_t DFE_CFG_SDM_PARAMETER; // 0x108
    __IOM uint32_t DFE_CFG_GPADC_START; // 0x10C
    __IOM uint32_t DFE_MNT_GPADC_DATA0; // 0x110
    __IOM uint32_t DFE_MNT_GPADC_DATA1; // 0x114
} rf_dfe_handle_t;

#define DFE_WORK_MODE_SHIFT         (0)
#define DFE_WORK_MODE_MASK          (0x3U << DFE_WORK_MODE_SHIFT)
#define DFE_WORK_MODE_VAL(x)        (((uint32_t)(x) << DFE_WORK_MODE_SHIFT) & DFE_WORK_MODE_MASK)
#define DFE_LINK_CTRL_MODE_SHIFT    (4)
#define DFE_LINK_CTRL_MODE_MASK     (0x1U << DFE_LINK_CTRL_MODE_SHIFT)
#define DFE_LINK_CTRL_MODE_VAL(x)   (((uint32_t)(x) << DFE_LINK_CTRL_MODE_SHIFT) & DFE_LINK_CTRL_MODE_MASK)

#define DFE_BW_SHIFT                (0)
#define DFE_BW_MASK                 (0x7U << DFE_BW_SHIFT)
#define DFE_BW_VAL(x)               (((uint32_t)(x) << DFE_BW_SHIFT) & DFE_BW_MASK)
#define DFE_RX_CLK_SEL_SHIFT        (4)
#define DFE_RX_CLK_SEL_MASK         (0x1U << DFE_RX_CLK_SEL_SHIFT)
#define DFE_RX_CLK_SEL_VAL(x)       (((uint32_t)(x) << DFE_RX_CLK_SEL_SHIFT) & DFE_RX_CLK_SEL_MASK)
#define DFE_LINE_CTRL_BW_SHIFT      (8)
#define DFE_LINE_CTRL_BW_MASK       (0x1U << DFE_LINE_CTRL_BW_SHIFT)
#define DFE_LINE_CTRL_BW_VAL(x)     (((uint32_t)(x) << DFE_LINE_CTRL_BW_SHIFT) & DFE_LINE_CTRL_BW_MASK)
#define DFE_RXIQ_SWAP_FLAG_SHIFT    (12)
#define DFE_RXIQ_SWAP_FLAG_MASK     (0x1U << DFE_RXIQ_SWAP_FLAG_SHIFT)
#define DFE_RXIQ_SWAP_FLAG_VAL(x)   (((uint32_t)(x) << DFE_RXIQ_SWAP_FLAG_SHIFT) & DFE_RXIQ_SWAP_FLAG_MASK)

#define DFE_TX_FIR59_BYPASS_SHIFT   (0)
#define DFE_TX_FIR59_BYPASS_MASK    (0x1U << DFE_TX_FIR59_BYPASS_SHIFT)
#define DFE_TX_FIR59_BYPASS_VAL(x)  (((uint32_t)(x) << DFE_TX_FIR59_BYPASS_SHIFT) & DFE_TX_FIR59_BYPASS_MASK)
#define DFE_FIR59_PLL_GEN_SHIFT     (4)
#define DFE_FIR59_PLL_GEN_MASK      (0x1U << DFE_FIR59_PLL_GEN_SHIFT)
#define DFE_FIR59_PLL_GEN_VAL(x)    (((uint32_t)(x) << DFE_FIR59_PLL_GEN_SHIFT) & DFE_FIR59_PLL_GEN_MASK)
#define DFE_FIR59_LINE_CTRL_PLL_GEN_SHIFT   (8)
#define DFE_FIR59_LINE_CTRL_PLL_GEN_MASK    (0x1U << DFE_FIR59_LINE_CTRL_PLL_GEN_SHIFT)
#define DFE_FIR59_LINE_CTRL_PLL_GEN_VAL(x)  (((uint32_t)(x) << DFE_FIR59_LINE_CTRL_PLL_GEN_SHIFT) & DFE_FIR59_LINE_CTRL_PLL_GEN_MASK)

#define DFE_DDC_FCW_SHIFT           (0)
#define DFE_DDC_FCW_MASK            (0x7FFFFFFU << DFE_DDC_FCW_SHIFT)
#define DFE_DDC_FCW_VAL(x)          (((uint32_t)(x) << DFE_DDC_FCW_SHIFT) & DFE_DDC_FCW_MASK)
#define DFE_DDC_BYPASS_SHIFT        (28)
#define DFE_DDC_BYPASS_MASK         (0x1U << DFE_DDC_BYPASS_SHIFT)
#define DFE_DDC_BYPASS_VAL(x)       (((uint32_t)(x) << DFE_DDC_BYPASS_SHIFT) & DFE_DDC_BYPASS_MASK)

#define DFE_CAL_EST_WAIT_SHIFT          (0)
#define DFE_CAL_EST_WAIT_MASK           (0xFFFFU << DFE_CAL_EST_WAIT_SHIFT)
#define DFE_CAL_EST_WAIT_VAL(x)         (((uint32_t)(x) << DFE_CAL_EST_WAIT_SHIFT) & DFE_CAL_EST_WAIT_MASK)
#define DFE_CAL_SEND_DURATION_SHIFT     (16)
#define DFE_CAL_SEND_DURATION_MASK      (0xFFFFU << DFE_CAL_SEND_DURATION_SHIFT)
#define DFE_CAL_SEND_DURATION_VAL(x)    (((uint32_t)(x) << DFE_CAL_SEND_DURATION_SHIFT) & DFE_CAL_SEND_DURATION_MASK)

#define DFE_CAL_EST_DC_MEAN_IDX_SHIFT   (0)
#define DFE_CAL_EST_DC_MEAN_IDX_MASK    (0x3U << DFE_CAL_EST_DC_MEAN_IDX_SHIFT)
#define DFE_CAL_EST_DC_MEAN_IDX_VAL(x)  (((uint32_t)(x) << DFE_CAL_EST_DC_MEAN_IDX_SHIFT) & DFE_CAL_EST_DC_MEAN_IDX_MASK)
#define DFE_CAL_EST_SINE_BUF_IDX_SHIFT  (4)
#define DFE_CAL_EST_SINE_BUF_IDX_MASK   (0x3U << DFE_CAL_EST_SINE_BUF_IDX_SHIFT)
#define DFE_CAL_EST_SINE_BUF_IDX_VAL(x) (((uint32_t)(x) << DFE_CAL_EST_SINE_BUF_IDX_SHIFT) & DFE_CAL_EST_SINE_BUF_IDX_MASK)
#define DFE_SINE_DC_SEL_SHIFT           (8)
#define DFE_SINE_DC_SEL_MASK            (0x1U << DFE_SINE_DC_SEL_SHIFT)
#define DFE_SINE_DC_SEL_VAL(x)          (((uint32_t)(x) << DFE_SINE_DC_SEL_SHIFT) & DFE_SINE_DC_SEL_MASK)

#define DFE_CAL_SEND_DC_VTQ_SHIFT       (0)
#define DFE_CAL_SEND_DC_VTQ_MASK        (0x1FFFU << DFE_CAL_SEND_DC_VTQ_SHIFT)
#define DFE_CAL_SEND_DC_VTQ_VAL(x)      (((uint32_t)(x) << DFE_CAL_SEND_DC_VTQ_SHIFT) & DFE_CAL_SEND_DC_VTQ_MASK)
#define DFE_CAL_SEND_DC_VTI_SHIFT       (16)
#define DFE_CAL_SEND_DC_VTI_MASK        (0x1FFFU << DFE_CAL_SEND_DC_VTI_SHIFT)
#define DFE_CAL_SEND_DC_VTI_VAL(x)      (((uint32_t)(x) << DFE_CAL_SEND_DC_VTI_SHIFT) & DFE_CAL_SEND_DC_VTI_MASK)

#define DFE_CAL_SEND_START_SHIFT        (0)
#define DFE_CAL_SEND_START_MASK         (0x1U << DFE_CAL_SEND_START_SHIFT)
#define DFE_CAL_SEND_START_VAL(x)       (((uint32_t)(x) << DFE_CAL_SEND_START_SHIFT) & DFE_CAL_SEND_START_MASK)

#define DFE_CAL_SEND_SINE_FCW_SHIFT     (0)
#define DFE_CAL_SEND_SINE_FCW_MASK      (0x7FFFFFFU << DFE_CAL_SEND_SINE_FCW_SHIFT)
#define DFE_CAL_SEND_SINE_FCW_VAL(x)    (((uint32_t)(x) << DFE_CAL_SEND_SINE_FCW_SHIFT) & DFE_CAL_SEND_SINE_FCW_MASK)

#define DFE_CAL_EST_FFT_FCW_SHIFT       (0)
#define DFE_CAL_EST_FFT_FCW_MASK        (0x7FFFFFFU << DFE_CAL_EST_FFT_FCW_SHIFT)
#define DFE_CAL_EST_FFT_FCW_VAL(x)      (((uint32_t)(x) << DFE_CAL_EST_FFT_FCW_SHIFT) & DFE_CAL_EST_FFT_FCW_MASK)

#define DFE_CAL_EST_FFT_FINISH_SHIFT    (0)
#define DFE_CAL_EST_FFT_FINISH_MASK     (0x1U << DFE_CAL_EST_FFT_FINISH_SHIFT)
#define DFE_CAL_EST_FFT_FINISH_VAL(x)   (((uint32_t)(x) << DFE_CAL_EST_FFT_FINISH_SHIFT) & DFE_CAL_EST_FFT_FINISH_MASK)
#define DFE_CAL_EST_DC_FINISH_SHIFT     (4)
#define DFE_CAL_EST_DC_FINISH_MASK      (0x1U << DFE_CAL_EST_DC_FINISH_SHIFT)
#define DFE_CAL_EST_DC_FINISH_VAL(x)    (((uint32_t)(x) << DFE_CAL_EST_DC_FINISH_SHIFT) & DFE_CAL_EST_DC_FINISH_MASK)
#define DFE_CAL_EST_SINE_WR_FINISH_SHIFT    (0)
#define DFE_CAL_EST_SINE_WR_FINISH_MASK     (0x1U << DFE_CAL_EST_SINE_WR_FINISH_SHIFT)
#define DFE_CAL_EST_SINE_WR_FINISH_VAL(x)   (((uint32_t)(x) << DFE_CAL_EST_SINE_WR_FINISH_SHIFT) & DFE_CAL_EST_SINE_WR_FINISH_MASK)

#define DFE_CAL_EST_DC_RSLT_SHIFT       (0)
#define DFE_CAL_EST_DC_RSLT_MASK        (0x3FFFU << DFE_CAL_EST_DC_RSLT_SHIFT)
#define DFE_CAL_EST_DC_RSLT_VAL(x)      (((uint32_t)(x) << DFE_CAL_EST_DC_RSLT_SHIFT) & DFE_CAL_EST_DC_RSLT_MASK)

#define DFE_CAL_EST_FFT_RSLTI_SHIFT     (0)
#define DFE_CAL_EST_FFT_RSLTI_MASK      (0x3FFFFFU << DFE_CAL_EST_FFT_RSLTI_SHIFT)
#define DFE_CAL_EST_FFT_RSLTI_VAL(x)    (((uint32_t)(x) << DFE_CAL_EST_FFT_RSLTI_SHIFT) & DFE_CAL_EST_FFT_RSLTI_MASK)

#define DFE_CAL_EST_FFT_RSLTQ_SHIFT     (0)
#define DFE_CAL_EST_FFT_RSLTQ_MASK      (0x3FFFFFU << DFE_CAL_EST_FFT_RSLTQ_SHIFT)
#define DFE_CAL_EST_FFT_RSLTQ_VAL(x)    (((uint32_t)(x) << DFE_CAL_EST_FFT_RSLTQ_SHIFT) & DFE_CAL_EST_FFT_RSLTQ_MASK)

#define DFE_RMDC0_BYPASS_SHIFT      (16)
#define DFE_RMDC0_BYPASS_MASK       (0x1U << DFE_RMDC0_BYPASS_SHIFT)
#define DFE_RMDC0_BYPASS_VAL(x)     (((uint32_t)(x) << DFE_RMDC0_BYPASS_SHIFT) & DFE_RMDC0_BYPASS_MASK)

#define DFE_RMDC1_BYPASS_SHIFT      (16)
#define DFE_RMDC1_BYPASS_MASK       (0x1U << DFE_RMDC1_BYPASS_SHIFT)
#define DFE_RMDC1_BYPASS_VAL(x)     (((uint32_t)(x) << DFE_RMDC1_BYPASS_SHIFT) & DFE_RMDC1_BYPASS_MASK)

#define DFE_CALIB_AMP_COMPQ_SHIFT   (0)
#define DFE_CALIB_AMP_COMPQ_MASK    (0x1FFFU << DFE_CALIB_AMP_COMPQ_SHIFT)
#define DFE_CALIB_AMP_COMPQ_VAL(x)  (((uint32_t)(x) << DFE_CALIB_AMP_COMPQ_SHIFT) & DFE_CALIB_AMP_COMPQ_MASK)
#define DFE_CALIB_AMP_COMPI_SHIFT   (16)
#define DFE_CALIB_AMP_COMPI_MASK    (0x1FFFU << DFE_CALIB_AMP_COMPI_SHIFT)
#define DFE_CALIB_AMP_COMPI_VAL(x)  (((uint32_t)(x) << DFE_CALIB_AMP_COMPI_SHIFT) & DFE_CALIB_AMP_COMPI_MASK)

#define DFE_CALIB_PHASE_COMP_SHIFT  (0)
#define DFE_CALIB_PHASE_COMP_MASK   (0xFFU << DFE_CALIB_PHASE_COMP_SHIFT)
#define DFE_CALIB_PHASE_COMP_VAL(x) (((uint32_t)(x) << DFE_CALIB_PHASE_COMP_SHIFT) & DFE_CALIB_PHASE_COMP_MASK)

#define DFE_CALIB_DC_COMPQ_SHIFT    (0)
#define DFE_CALIB_DC_COMPQ_MASK     (0xFFU << DFE_CALIB_DC_COMPQ_SHIFT)
#define DFE_CALIB_DC_COMPQ_VAL(x)   (((uint32_t)(x) << DFE_CALIB_DC_COMPQ_SHIFT) & DFE_CALIB_DC_COMPQ_MASK)
#define DFE_CALIB_DC_COMPI_SHIFT    (16)
#define DFE_CALIB_DC_COMPI_MASK     (0xFFU << DFE_CALIB_DC_COMPI_SHIFT)
#define DFE_CALIB_DC_COMPI_VAL(x)   (((uint32_t)(x) << DFE_CALIB_DC_COMPI_SHIFT) & DFE_CALIB_DC_COMPI_MASK)

#define RF_CTRL_CLK_ME_SHIFT    (16)
#define RF_CTRL_CLK_ME_MASK     (0x1U << RF_CTRL_CLK_ME_SHIFT)
#define RF_CTRL_CLK_ME_VAL(x)   (((uint32_t)(x) << RF_CTRL_CLK_ME_SHIFT) & RF_CTRL_CLK_ME_MASK)
#define RF_CTRL_CLK_MO_SHIFT    (0)
#define RF_CTRL_CLK_MO_MASK     (0x1U << RF_CTRL_CLK_MO_SHIFT)
#define RF_CTRL_CLK_MO_VAL(x)   (((uint32_t)(x) << RF_CTRL_CLK_MO_SHIFT) & RF_CTRL_CLK_MO_MASK)

#define RF_CTRL_RXEN_ME_SHIFT    (17)
#define RF_CTRL_RXEN_ME_MASK     (0x1U << RF_CTRL_RXEN_ME_SHIFT)
#define RF_CTRL_RXEN_ME_VAL(x)   (((uint32_t)(x) << RF_CTRL_RXEN_ME_SHIFT) & RF_CTRL_RXEN_ME_MASK)
#define RF_CTRL_RXEN_MO_SHIFT    (1)
#define RF_CTRL_RXEN_MO_MASK     (0x1U << RF_CTRL_RXEN_MO_SHIFT)
#define RF_CTRL_RXEN_MO_VAL(x)   (((uint32_t)(x) << RF_CTRL_RXEN_MO_SHIFT) & RF_CTRL_RXEN_MO_MASK)

#define RF_CTRL_TXEN_ME_SHIFT    (16)
#define RF_CTRL_TXEN_ME_MASK     (0x1U << RF_CTRL_TXEN_ME_SHIFT)
#define RF_CTRL_TXEN_ME_VAL(x)   (((uint32_t)(x) << RF_CTRL_TXEN_ME_SHIFT) & RF_CTRL_TXEN_ME_MASK)
#define RF_CTRL_TXEN_MO_SHIFT    (0)
#define RF_CTRL_TXEN_MO_MASK     (0x1U << RF_CTRL_TXEN_MO_SHIFT)
#define RF_CTRL_TXEN_MO_VAL(x)   (((uint32_t)(x) << RF_CTRL_TXEN_MO_SHIFT) & RF_CTRL_TXEN_MO_MASK)

#define DFE_CTRL_WORK_MODE_SHIFT    (4)
#define DFE_CTRL_WORK_MODE_MASK     (0x1U << DFE_CTRL_WORK_MODE_SHIFT)
#define DFE_CTRL_WORK_MODE_VAL(x)   (((uint32_t)(x) << DFE_CTRL_WORK_MODE_SHIFT) & DFE_CTRL_WORK_MODE_MASK)

#define DFE_CFG_CTRL_BW_SHIFT    (8)
#define DFE_CFG_CTRL_BW_MASK     (0x1U << DFE_CFG_CTRL_BW_SHIFT)
#define DFE_CFG_CTRL_BW_VAL(x)   (((uint32_t)(x) << DFE_CFG_CTRL_BW_SHIFT) & DFE_CFG_CTRL_BW_MASK)
#define DFE_CFG_BW_SHIFT        (0)
#define DFE_CFG_BW_MASK         (0x7U << DFE_CFG_BW_SHIFT)
#define DFE_CFG_BW_VAL(x)       (((uint32_t)(x) << DFE_CFG_BW_SHIFT) & DFE_CFG_BW_MASK)

#define RF_CTRL_TXMODE_ME_SHIFT    (24)
#define RF_CTRL_TXMODE_ME_MASK     (0x1U << RF_CTRL_TXMODE_ME_SHIFT)
#define RF_CTRL_TXMODE_ME_VAL(x)   (((uint32_t)(x) << RF_CTRL_TXMODE_ME_SHIFT) & RF_CTRL_TXMODE_ME_MASK)
#define RF_CTRL_TXMODE_MO_SHIFT    (8)
#define RF_CTRL_TXMODE_MO_MASK     (0x1U << RF_CTRL_TXMODE_MO_SHIFT)
#define RF_CTRL_TXMODE_MO_VAL(x)   (((uint32_t)(x) << RF_CTRL_TXMODE_MO_SHIFT) & RF_CTRL_TXMODE_MO_MASK)

typedef struct
{
    __IOM uint32_t DCOC_I_CTRL;         // 0x00
    __IOM uint32_t DCOC_I_LUT_L0B0_3;   // 0x04
    __IOM uint32_t DCOC_I_LUT_L0B4_7;   // 0x08
    __IOM uint32_t DCOC_I_LUT_L0B8_10;  // 0x0C
    __IOM uint32_t DCOC_I_LUT_L0B12;    // 0x10
    __IOM uint32_t DCOC_I_LUT_L1B0_3;   // 0x14
    __IOM uint32_t DCOC_I_LUT_L1B4_7;   // 0x18
    __IOM uint32_t DCOC_I_LUT_L1B8_10;  // 0x1C
    __IOM uint32_t DCOC_I_LUT_L1B12;    // 0x20
    __IOM uint32_t DCOC_I_LUT_L2B0_3;   // 0x24
    __IOM uint32_t DCOC_I_LUT_L2B4_7;   // 0x28
    __IOM uint32_t DCOC_I_LUT_L2B8_10;  // 0x2C
    __IOM uint32_t DCOC_I_LUT_L2B12;    // 0x30
    __IOM uint32_t DCOC_I_LUT_L3B0_3;   // 0x34
    __IOM uint32_t DCOC_I_LUT_L3B4_7;   // 0x38
    __IOM uint32_t DCOC_I_LUT_L3B8_10;  // 0x3C
    __IOM uint32_t DCOC_I_LUT_L3B12;    // 0x40
    __IOM uint32_t DCOC_I_LUT_L4B0_3;   // 0x44
    __IOM uint32_t DCOC_I_LUT_L4B4_7;   // 0x48
    __IOM uint32_t DCOC_I_LUT_L4B8_10;  // 0x4C
    __IOM uint32_t DCOC_I_LUT_L4B12;    // 0x50
    __IOM uint32_t DCOC_I_LUT_L5B0_3;   // 0x54
    __IOM uint32_t DCOC_I_LUT_L5B4_7;   // 0x58
    __IOM uint32_t DCOC_I_LUT_L5B8_10;  // 0x5C
    __IOM uint32_t DCOC_I_LUT_L5B12;    // 0x60
    __IOM uint32_t DCOC_I_LUT_L6B0_3;   // 0x64
    __IOM uint32_t DCOC_I_LUT_L6B4_7;   // 0x68
    __IOM uint32_t DCOC_I_LUT_L6B8_10;  // 0x6C
    __IOM uint32_t DCOC_I_LUT_L6B12;    // 0x70
    __IOM uint32_t DCOC_I_LUT_L7B0_3;   // 0x74
    __IOM uint32_t DCOC_I_LUT_L7B4_7;   // 0x78
    __IOM uint32_t DCOC_I_LUT_L7B8_10;  // 0x7C
    __IOM uint32_t DCOC_I_LUT_L7B12;    // 0x80
    __IOM uint32_t DCOC_I_LUT_L8B0_3;   // 0x84
    __IOM uint32_t DCOC_I_LUT_L8B4_7;   // 0x88
    __IOM uint32_t DCOC_I_LUT_L8B8_10;  // 0x8C
    __IOM uint32_t DCOC_I_LUT_L8B12;    // 0x90
    __IOM uint32_t DCOC_I_LUT_L9B0_3;   // 0x94
    __IOM uint32_t DCOC_I_LUT_L9B4_7;   // 0x98
    __IOM uint32_t DCOC_I_LUT_L9B8_10;  // 0x9C
    __IOM uint32_t DCOC_I_LUT_L9B12;    // 0xA0
    __IOM uint32_t DCOC_I_LUT_L10B0_3;  // 0xA4
    __IOM uint32_t DCOC_I_LUT_L10B4_7;  // 0xA8
    __IOM uint32_t DCOC_I_LUT_L10B8_10; // 0xAC
    __IOM uint32_t DCOC_I_LUT_L10B12;   // 0xB0
} rf_dcoc_i_handle_t;

typedef struct
{
    __IOM uint32_t DCOC_Q_CTRL;         // 0x00
    __IOM uint32_t DCOC_Q_LUT_L0B0_3;   // 0x04
    __IOM uint32_t DCOC_Q_LUT_L0B4_7;   // 0x08
    __IOM uint32_t DCOC_Q_LUT_L0B8_10;  // 0x0C
    __IOM uint32_t DCOC_Q_LUT_L0B12;    // 0x10
    __IOM uint32_t DCOC_Q_LUT_L1B0_3;   // 0x14
    __IOM uint32_t DCOC_Q_LUT_L1B4_7;   // 0x18
    __IOM uint32_t DCOC_Q_LUT_L1B8_10;  // 0x1C
    __IOM uint32_t DCOC_Q_LUT_L1B12;    // 0x20
    __IOM uint32_t DCOC_Q_LUT_L2B0_3;   // 0x24
    __IOM uint32_t DCOC_Q_LUT_L2B4_7;   // 0x28
    __IOM uint32_t DCOC_Q_LUT_L2B8_10;  // 0x2C
    __IOM uint32_t DCOC_Q_LUT_L2B12;    // 0x30
    __IOM uint32_t DCOC_Q_LUT_L3B0_3;   // 0x34
    __IOM uint32_t DCOC_Q_LUT_L3B4_7;   // 0x38
    __IOM uint32_t DCOC_Q_LUT_L3B8_10;  // 0x3C
    __IOM uint32_t DCOC_Q_LUT_L3B12;    // 0x40
    __IOM uint32_t DCOC_Q_LUT_L4B0_3;   // 0x44
    __IOM uint32_t DCOC_Q_LUT_L4B4_7;   // 0x48
    __IOM uint32_t DCOC_Q_LUT_L4B8_10;  // 0x4C
    __IOM uint32_t DCOC_Q_LUT_L4B12;    // 0x50
    __IOM uint32_t DCOC_Q_LUT_L5B0_3;   // 0x54
    __IOM uint32_t DCOC_Q_LUT_L5B4_7;   // 0x58
    __IOM uint32_t DCOC_Q_LUT_L5B8_10;  // 0x5C
    __IOM uint32_t DCOC_Q_LUT_L5B12;    // 0x60
    __IOM uint32_t DCOC_Q_LUT_L6B0_3;   // 0x64
    __IOM uint32_t DCOC_Q_LUT_L6B4_7;   // 0x68
    __IOM uint32_t DCOC_Q_LUT_L6B8_10;  // 0x6C
    __IOM uint32_t DCOC_Q_LUT_L6B12;    // 0x70
    __IOM uint32_t DCOC_Q_LUT_L7B0_3;   // 0x74
    __IOM uint32_t DCOC_Q_LUT_L7B4_7;   // 0x78
    __IOM uint32_t DCOC_Q_LUT_L7B8_10;  // 0x7C
    __IOM uint32_t DCOC_Q_LUT_L7B12;    // 0x80
    __IOM uint32_t DCOC_Q_LUT_L8B0_3;   // 0x84
    __IOM uint32_t DCOC_Q_LUT_L8B4_7;   // 0x88
    __IOM uint32_t DCOC_Q_LUT_L8B8_10;  // 0x8C
    __IOM uint32_t DCOC_Q_LUT_L8B12;    // 0x90
    __IOM uint32_t DCOC_Q_LUT_L9B0_3;   // 0x94
    __IOM uint32_t DCOC_Q_LUT_L9B4_7;   // 0x98
    __IOM uint32_t DCOC_Q_LUT_L9B8_10;  // 0x9C
    __IOM uint32_t DCOC_Q_LUT_L9B12;    // 0xA0
    __IOM uint32_t DCOC_Q_LUT_L10B0_3;  // 0xA4
    __IOM uint32_t DCOC_Q_LUT_L10B4_7;  // 0xA8
    __IOM uint32_t DCOC_Q_LUT_L10B8_10; // 0xAC
    __IOM uint32_t DCOC_Q_LUT_L10B12;   // 0xB0
} rf_dcoc_q_handle_t;

#endif
